### ISSUE TITLE
System Class Feature Requests

### ISSUE THREAD

**Issue by jgoppert** [pydy/pydy#100]
1. I work a lot with  attitude kinematics which require a lot of adjustments after integrating such as quaternion normalization or wrapping euler angles. It would be good if you could include a hook for cleanup after each integration step. 

2. For most control problems the continuous dynamics are only half the battle and most users turn to something like simulink to handle the digital control simulation. I'm currently creating a pure python simulation of an autopilot. I would love to see PyDy hook in well with digital simulations such as this: http://nbviewer.ipython.org/github/jgoppert/PX4-SIL/blob/master/PeriodicSim.ipynb
The way I'm doing this currently is I have an object called ContinuousDynamics that acts like your System class. I have a periodic scheduler that runs all the processes such as control at a fixed period. Whenever the simulated vehicle dynamics are needed, they are integrated using scipy.ode.integrate.

I was originally talking with @moorepants about this on a sympy pull request but realized I got a bit off topic and this seemed like a more appropriate place to post.

**Comment by moorepants** [comment]
@jgoppert I'm closing this. Please reopen if you want to contribute this feature. I'm not sure of exactly what you are proposing but if you can write up an example maybe we can judge it. Pull requests are welcome too.
