### ISSUE TITLE
Change TrackBallControls.js to OrbitControls.js

### ISSUE THREAD

**Issue by moorepants** [pydy/pydy#101]
Seems like this is a newer and better version of what TrackBallControls.js is.

https://github.com/mrdoob/three.js/blob/master/examples/js/controls/OrbitControls.js

**Comment by tarzzz** [comment]
Seems like implementing OrbitControls might hinder our existing functionality (Reset Camera Button etc.)

http://stackoverflow.com/questions/18581225/orbitcontrol-or-trackballcontrol

Maybe Orbit might have better performance, but not sure whether we need to migrate.

**Comment by moorepants** [comment]
Ok, let's close this for now then. I thought I read at some point that orbitcontrols.js was meant to take the place of trackballcontrols.js and be better. Sounds like it isn't. This is not necessary for the release milestone either.
