### ISSUE TITLE
Get the PyDy docs back online at readthedocs.org

### ISSUE THREAD

**Issue by moorepants** [pydy/pydy#112]

**Comment by chrisdembia** [comment]
I gave readthedocs write access to all my repos...doesn't seem like that should have been necessary!

**Comment by chrisdembia** [comment]
I asked readthedocs about their permissions here https://github.com/rtfd/readthedocs.org/issues/1149

**Comment by chrisdembia** [comment]
I decided to revoke readthedocs' access to my github account. This might mean that docs will not be automatically regenerated upon merges to master, and need to be triggered manually. We can investigate that later.

**Comment by moorepants** [comment]
I have a readthedocs setup with pydy i think. I have you as an owner, chris.

**Comment by chrisdembia** [comment]
Done: http://pydy.readthedocs.org/en/latest/

I don't know if it automatically updates though...
