### ISSUE TITLE
outdated Readme and Ipython notebook examples

### ISSUE THREAD

**Issue by sahilshekhawat** [pydy/pydy#114]
The main Readme is outdated, there is not ``docs/src`` folder, moreover all the Ipython's notebook examples are of v3, thus outdated.

**Comment by moorepants** [comment]
What do you mean all notebook examples are of v3? v3 of what?

**Comment by sahilshekhawat** [comment]
v3 of Ipython notebook,  we need to convert them to v4.

**Comment by chrisdembia** [comment]
Thanks @sahilshekhawat . Would you be interested in doing that?

**Comment by moorepants** [comment]
Actually, we need to decide what versions of IPython we want to support. Right now it says we support as far back as 0.13 in the README. No one has checked this, so there are notebooks of all version.

Tarun merged code in this summer that may require IPython 3.0, but it would be nice to support IPython 2.0.

IPython backports the notebook formats. We will need to agree what version of IPython and what version of the notebook format will be required for the examples.

**Comment by moorepants** [comment]
Relevant issues:
- https://github.com/pydy/pydy/issues/87
- https://github.com/pydy/pydy/pull/90

**Comment by sahilshekhawat** [comment]
Oh!  Okay,  I thought it might be a problem. BUT we need to update Readme.

**Comment by moorepants** [comment]
One other issue is that IPython 3 isn't even release yet. I think they are in beta, so until they release 3.0 the README should include the dev install instructions for the HEAD of master, which Tarun has an open PR for: PR #90

**Comment by moorepants** [comment]
PR #123 addresses the README.

**Comment by moorepants** [comment]
We need to check whether all of the examples work before the release. I'm just going to make an new issue for that and close this one.
