### ISSUE TITLE
Adjust System to support the new generate_ode_function.

### ISSUE THREAD

**Issue by moorepants** [pydy/pydy#116]
System is setup to use the now deprecated function `generate_ode_function` from the `pydy.codegen.code` module. It needs to be changed to use `pydy.codegen.ode_function_generators.generate_ode_function`.

**Comment by jinankjain** [comment]
Hi, I am newbie and I was trying to fix this bug and when I changed from .codegen.code to .codegen.ode_function_generators but when I ran the tests there were 4 test case which failed could you please help in that.

http://pastie.org/10005485

**Comment by moorepants** [comment]
I think it is supposed to be "specifieds".

**Comment by moorepants** [comment]
We may need something for backwards compatibility. It should probably support both versions for now and we deprecate (issue a warning) if the user uses "specified".

**Comment by jinankjain** [comment]
What sort of warning message needs to come could you help me in that?

**Comment by moorepants** [comment]
If a user uses the value `specified` anywhere instead of `specifieds` we should allow it, but issue a warning say that `specified` is deprecated and will not work in future versions.

**Comment by jinankjain** [comment]
I have just tried to write a patch for it could you please review it.

**Comment by jinankjain** [comment]
Have you looked at the patch ?

**Comment by jinankjain** [comment]
Hi Jason,

Could please tell me what went wrong in my new patch I was not able to figure out why nosetest case are failing

**Comment by sahilshekhawat** [comment]
@moorepants Can we close this now?

**Comment by moorepants** [comment]
Yes!
