### ISSUE TITLE
Starting using the PEP 440 dev version standard.

### ISSUE THREAD

**Issue by moorepants** [pydy/pydy#121]

**Comment by jinankjain** [comment]
I did not get what needs to done to fix this issue could you please me in that.

**Comment by moorepants** [comment]
PEP 440 introduced specific versioning rules. Right now our dev versions don't follow that rule. For example the dev version should probably be 0.3.0.dev write now (i.e. any commit after 0.2.1). I'm a little fuzzy on this though. Maybe read PEP 440 to understand better.

**Comment by jinankjain** [comment]
Could you please look at this patch is it fine
