### ISSUE TITLE
kane._q and kane._u changed from lists to matrices in SymPy 0.7.6

### ISSUE THREAD

**Issue by coolyashish** [pydy/pydy#138]
Hi I tried to create visualization for three_link_canical_pendulums but I couldn't due to type error. 

Commands to produce error:
1. Go to /pydy/examples/three_link_conical_pendulum
2. python simulate.py ..
3. python visualize.py
TypeError...

Error Logs: https://gist.github.com/coolyashish/c48909e428b3e05c94a9

**Comment by moorepants** [comment]
@tarzzz You have any idea?

**Comment by tarzzz** [comment]
@moorepants I have been closely looking at this particular issue. 
We have 31 arguments, i.e. 6 kane._q's, 6 kane._u's and 19 parameters(lengths, masses and inerties etc.). I fail to understand why is the numeric transform function requires only 25. Somehow it is neglecting some of parameters. Still looking into it.

**Comment by tarzzz** [comment]
Ok, Here is my observation. When we do `kane._q + kane._u`, we get this:

    Matrix([[alpha0(t) + omega0(t)], [alpha1(t) + omega1(t)], [alpha2(t) + omega2(t)], [beta0(t) + delta0(t)], [beta1(t) + delta1(t)], [beta2(t) + delta2(t)]])

Instead of what should have been:

    Matrix([alpha0(t),alpha1(t), alpha2(t), beta0(t), beta1(t), beta2(t), omega0(t), omega1(t), omega2(t), delta0(t), delta1(t), delta2(t)])

This is because, a print on kane._q, and kane._u gives:

    Matrix([[alpha0(t)], [alpha1(t)], [alpha2(t)], [beta0(t)], [beta1(t)], [beta2(t)]])

and 
    
    Matrix([[omega0(t)], [omega1(t)], [omega2(t)], [delta0(t)], [delta1(t)], [delta2(t)]])

It is a list of lists, which is *probably* causing the issue. @moorepants Could you please confirm if any recent change in KanesMethod might have caused it? We can do a quick fix here, but instead we should look into the buggy code!

**Comment by tarzzz** [comment]
@coolyashish : As a quick fix, you can do this:

In the example's `visualize.py` replace:

    scene.generate_visualization_json(kane._q + kane._u, param_syms,
                                  state_trajectories, param_vals)

with:

    l = []
    l+= [i for i in kane._q]
    l+= [i for i in kane._u]
    scene.generate_visualization_json(l, param_syms,
                                  state_trajectories, param_vals)

**Comment by moorepants** [comment]
In sympy 0.7.6 kane._q and kane._u were changed from lists to matrices. You can simply do `kane._q[:]` to get the list form. There are a couple of issues here.
1. kane.q and kane.u should be public variables.
2. We shouldn't write code that relies on private variables.

**Comment by moorepants** [comment]
There are several instances: https://github.com/pydy/pydy/search?utf8=%E2%9C%93&q=kane._q

We need to fix them.

**Comment by moorepants** [comment]
Here is an example of dealing with this:

https://github.com/pydy/pydy/blob/ada06d1f3bbd3ef85cb851dc26abdc9cb4e880b8/pydy/tests/test_system.py#L81

**Comment by moorepants** [comment]
Issue in SymPy: https://github.com/sympy/sympy/issues/7933

**Comment by tarzzz** [comment]
Can be closed, since it is on SymPy's end, and we have referenced it as well.

**Comment by moorepants** [comment]
No I think we need to fix the examples in PyDy because they fail depending on which SymPy you use.

**Comment by moorepants** [comment]
Instances of these variables:

```
moorepants@moorepants-2170p:pydy(issue-138)$ grep -r "\._q " --include=\*.py pydy
pydy/system.py:            insyms = set(self.eom_method._q + self.eom_method._qdot +
pydy/tests/test_system.py:            assert self.sys.states == self.kane._q + self.kane._u
moorepants@moorepants-2170p:pydy(issue-138)$ grep -r "\._q " --include=\*.{ipynb,py} examples/
examples/three_link_conical_pendulum/visualize.py:scene.generate_visualization_json(kane._q + kane._u, param_syms,
examples/mass_spring/code_gen.py:    dynamic = kane._q + kane._u
```
