### ISSUE TITLE
Skip the solve step if the mass matrix is identity or it is not provided

### ISSUE THREAD

**Issue by moorepants** [pydy/pydy#14]
_Issue by **[moorepants](https://github.com/moorepants)** from Wednesday Feb 12, 2014 at 22:57 GMT_
_Originally opened as https://github.com/pydy/pydy-code-gen/issues/21_

----

Right now the numpy.linalg.solve step is a slow down for any of these methods.

If the user solves the for M^-1 * F analytically then we don't need that. This can speed up things right now.

Later on we need to push the solve step to a low level in the generators so there is no python overhead. I'm not sure that the full mass matrix and forcing vector need to be used like this either, especially when the q dots equal the u's, then there is no reason to solve the full system. Finally, we need to do some learning and thinking about the Jain method in which you supposedly don't even have to form the mass matrix and do this solver.

**Comment by moorepants** [comment]
Addressed in PR #113.

**Comment by jcrist** [comment]
closed by #113
