### ISSUE TITLE
Notebook visualizations no longer work now that IPython 3.0 is released.

### ISSUE THREAD

**Issue by moorepants** [pydy/pydy#142]
This is some of the problem:

http://ipython.org/ipython-doc/3/whatsnew/version3_widget_migration.html

This notebook should work:

http://nbviewer.ipython.org/gist/moorepants/aab1a1c6b49f51718a90

**Comment by moorepants** [comment]
Note this too: http://ipython.org/ipython-doc/3/whatsnew/version3_widget_migration.html#python

Sounds like we are providing the JS incorrectly.

**Comment by jcrist** [comment]
Apparently my frustration with this issue was greater than my need for sleep... Here's what I've found:

Using Jason's PR for this issue, I'm able to get the visualizer to start in IPython 3.0 with no errors. The view boxes show up, and are readable, although they are enclosed in a horizontal slider box that's way more horizontally narrow than it needs to be. This is not a major issue though. Running the simulation shows nothing happening, and I can't move the view orientation.

If I try running just `scene.display()`, I have to open a page for localhost whatever myself (the code doesn't do it for me), and then enter in a filename for the json file. This is annoying, but not a deal breaker. I still can't move the viewer, and nothing shows up.

I'm often asked if I want to rewrite the contents of the static folder. From what I understand, `static` is just the webpage stuff, and nothing simulation specific. We should probably either store this in some fixed location, or write it to a temporary directory? Or maybe I'm wrong about this.

At one point, I actually got html request errors spilling onto the IPython notebook output cell. This may help with debugging. It looks like some file structure is missing/being requested from a wrong location:

```
127.0.0.1 - - [11/Mar/2015 01:29:18] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [11/Mar/2015 01:29:18] "GET /css/bootstrap.min.css HTTP/1.1" 200 -
127.0.0.1 - - [11/Mar/2015 01:29:18] "GET /css/slider.css HTTP/1.1" 200 -
127.0.0.1 - - [11/Mar/2015 01:29:18] "GET /css/main.css HTTP/1.1" 200 -
127.0.0.1 - - [11/Mar/2015 01:29:18] "GET /css/codemirror/codemirror.css HTTP/1.1" 200 -
127.0.0.1 - - [11/Mar/2015 01:29:18] "GET /css/codemirror/blackboard.css HTTP/1.1" 200 -
127.0.0.1 - - [11/Mar/2015 01:29:18] "GET /js/external/jquery/jquery.min.js HTTP/1.1" 200 -
127.0.0.1 - - [11/Mar/2015 01:29:18] "GET /js/external/bootstrap/bootstrap.min.js HTTP/1.1" 200 -
127.0.0.1 - - [11/Mar/2015 01:29:18] "GET /js/external/codemirror/codemirror.js HTTP/1.1" 200 -
127.0.0.1 - - [11/Mar/2015 01:29:18] "GET /js/external/jquery/jquery-ui.js HTTP/1.1" 200 -
127.0.0.1 - - [11/Mar/2015 01:29:18] "GET /js/external/three/three.min.js HTTP/1.1" 200 -
127.0.0.1 - - [11/Mar/2015 01:29:18] code 404, message File not found
127.0.0.1 - - [11/Mar/2015 01:29:18] "GET /js/external/three/three-r67.min.js HTTP/1.1" 404 -
127.0.0.1 - - [11/Mar/2015 01:29:18] "GET /js/external/three/TrackballControls.js HTTP/1.1" 200 -
127.0.0.1 - - [11/Mar/2015 01:29:18] "GET /js/external/utils/modernizr-2.0.6.js HTTP/1.1" 200 -
127.0.0.1 - - [11/Mar/2015 01:29:18] "GET /js/external/utils/bootstrap-slider.js HTTP/1.1" 200 -
127.0.0.1 - - [11/Mar/2015 01:29:18] "GET /js/external/utils/prototype.js HTTP/1.1" 200 -
127.0.0.1 - - [11/Mar/2015 01:29:18] "GET /js/external/codemirror/javascript-mode.js HTTP/1.1" 200 -
127.0.0.1 - - [11/Mar/2015 01:29:18] "GET /js/dyviz/dv.js HTTP/1.1" 200 -
127.0.0.1 - - [11/Mar/2015 01:29:18] "GET /js/dyviz/scene.js HTTP/1.1" 200 -
127.0.0.1 - - [11/Mar/2015 01:29:18] "GET /js/dyviz/parser.js HTTP/1.1" 200 -
127.0.0.1 - - [11/Mar/2015 01:29:18] "GET /js/dyviz/param_editor.js HTTP/1.1" 200 -
127.0.0.1 - - [11/Mar/2015 01:29:18] "GET /js/dyviz/materials.js HTTP/1.1" 200 -
127.0.0.1 - - [11/Mar/2015 01:29:18] "GET /js/dyviz/main.js HTTP/1.1" 200 -
127.0.0.1 - - [11/Mar/2015 01:29:18] code 404, message File not found
127.0.0.1 - - [11/Mar/2015 01:29:18] "GET /js/external/three/three-r67.min.js HTTP/1.1" 404 -
127.0.0.1 - - [11/Mar/2015 01:29:18] "GET /textures/checkerboard.jpg HTTP/1.1" 200 -
127.0.0.1 - - [11/Mar/2015 01:29:18] "GET /textures/metal.jpg HTTP/1.1" 200 -
127.0.0.1 - - [11/Mar/2015 01:29:18] "GET /textures/moon.jpg HTTP/1.1" 200 -
127.0.0.1 - - [11/Mar/2015 01:29:18] "GET /textures/earth.jpg HTTP/1.1" 200 -
127.0.0.1 - - [11/Mar/2015 01:29:18] "GET /textures/grass.jpg HTTP/1.1" 200 -
127.0.0.1 - - [11/Mar/2015 01:29:18] "GET /textures/dirt.jpg HTTP/1.1" 200 -
127.0.0.1 - - [11/Mar/2015 01:29:18] "GET /textures/water.jpg HTTP/1.1" 200 -
127.0.0.1 - - [11/Mar/2015 01:29:18] "GET /textures/lavatile.jpg HTTP/1.1" 200 -
127.0.0.1 - - [11/Mar/2015 01:29:18] "GET /fonts/glyphicons-halflings-regular.woff HTTP/1.1" 200 -
127.0.0.1 - - [11/Mar/2015 01:29:20] code 404, message File not found
127.0.0.1 - - [11/Mar/2015 01:29:20] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [11/Mar/2015 01:29:20] code 404, message File not found
127.0.0.1 - - [11/Mar/2015 01:29:20] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [11/Mar/2015 01:29:38] "GET /2015-03-11_01:28:14_scene_desc.json HTTP/1.1" 200 
```

I'm actually going to go to bed now, I'll work on this more in the morning.

**Comment by moorepants** [comment]
Jim, I suspect this is the main issue:

http://ipython.org/ipython-doc/3/whatsnew/version3_widget_migration.html#python

We load the javascript with `Javascript` and `Display` and it seems they may or may not be supported anymore. I'm not sure why the ipython docs recommend switching to private methods instead, nor do I like the idea of having the user install the js code in their extension home directory. We'd like to keep the js code with the python app.

I think you should simply chose an ipython2 dev commit around the date of Tarun's PR submissions. The `display_ipython` call will probably work just fine and you'll be able to show the demo.

**Comment by moorepants** [comment]
@tarzzz We finally have a user! And some bugs reported!

:)

**Comment by tarzzz** [comment]
Acknowledged! :)
Will look into it. My main priority is to get viz working before Jim's
Presentations.

**Comment by moorepants** [comment]
@tarzzz Introduced a commit (https://github.com/pydy/pydy/commit/770bfdd4f4f0c2ff8894c4e3e1e106a9185ee1f9) that disables adding the cameras, which "fixes" this issue, but now cameras don't work.

**Comment by moorepants** [comment]
See issue #151 for details about the camera break.

**Comment by moorepants** [comment]
On master with `examples/mass_spring_damper/mass_spring_damper.ipynb` I'm getting this visualization error, so it seems to me there may be more to it than the camera issue:

```
WARNING: "ContainerWidget" is deprecated, please use "Box" instead.
WARNING: "FloatTextWidget" is deprecated, please use "FloatText" instead.
WARNING: "ButtonWidget" is deprecated, please use "Button" instead.
WARNING: "HTMLWidget" is deprecated, please use "HTML" instead.

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-30-a0d8d478ebc7> in <module>()
----> 1 scene.display_ipython()

/home/moorepants/src/pydy/pydy/viz/scene.pyc in display_ipython(self)
    511         self.html_widget = widgets.HTMLWidget(value=html_file.read().format(load_url='static/' + self.scene_json_file))
    512         self.container.children = components
--> 513         self.container.set_css({"max-height": "10em",
    514                                 "overflow-y": "scroll",
    515                                 "display":"block"

AttributeError: 'ContainerWidget' object has no attribute 'set_css'

```

**Comment by tarzzz** [comment]
The widget names have changed since the 3.0 Release. We need to change the class names according to the version of IPython detected.

**Comment by moorepants** [comment]
This is the current traceback in the double pendulum example:
![selection_084](https://cloud.githubusercontent.com/assets/276007/7841240/10f12908-0450-11e5-9fb9-174034ba31ce.png)
