### ISSUE TITLE
We should likely join NumFOCUS

### ISSUE THREAD

**Issue by moorepants** [pydy/pydy#144]
http://numfocus.org/projects/join-as-project.html

**Comment by jinankjain** [comment]
In this we have to just write a proposal to them. Am I right ?

**Comment by moorepants** [comment]
Please see the mailing list. People are working on this.

**Comment by tarzzz** [comment]
We can close this as well!

**Comment by moorepants** [comment]
No we can't. This has never been done.

**Comment by jcrist** [comment]
Oh yeah, I did this. Per the people I talked to, there's no reason to join NumFocus. All our financials are covered by SymPy, we don't bring in any money on our own, and we don't have a very large user base. I was told we should just stay under SymPy for now.

**Comment by moorepants** [comment]
Ok great. Thanks Jim!
