### ISSUE TITLE
cython generator can create lots of files

### ISSUE THREAD

**Issue by moorepants** [pydy/pydy#15]
_Issue by **[moorepants](https://github.com/moorepants)** from Wednesday Feb 12, 2014 at 23:29 GMT_
_Originally opened as https://github.com/pydy/pydy-code-gen/issues/22_

----

These should be in a hidden directory and some thought about how to delete ones that are no longer useful or are identical needs to happen.

**Comment by moorepants** [comment]
Addressed in PR #113.

**Comment by jcrist** [comment]
Closed by #113
