### ISSUE TITLE
Cameras Not working in Master

### ISSUE THREAD

**Issue by tarzzz** [pydy/pydy#151]
The `addCamera` method in [L126](https://github.com/pydy/pydy/blob/master/pydy/viz/static/js/dyviz/scene.js#L126) messes up with the `_addDefaultCamera` method in [L48](https://github.com/pydy/pydy/blob/master/pydy/viz/static/js/dyviz/scene.js#L48). This leads to Cameras freezing once the animation starts/objects are loaded. As a temporary workaround, I have removed the addCamera functionality. As a result, the cameras passed into JSON object are not added to the scene.

**Comment by moorepants** [comment]
Note that this issue already mentioned this: https://github.com/pydy/pydy/issues/94

**Comment by moorepants** [comment]
I suggest removing the camera functionality to a PR since it is a broken feature. We shouldn't have broken stuff in master.
