### ISSUE TITLE
Determine the minimum IPython version dependency and declare it

### ISSUE THREAD

**Issue by moorepants** [pydy/pydy#155]
Ideally this would work with IPython 2.0-3.0 since 3.0 is so new.

**Comment by moorepants** [comment]
We also need to decide if IPython is an optional dependency or not. Currently we could make it optional because the visualization can be run without IPython.

**Comment by chrisdembia** [comment]
What's a specific test to determine if the ipython version is sufficient?

**Comment by moorepants** [comment]
I'd run the mass_spring_damper example and see how far back in IPython 2 we can go. But there is this issue #198.

**Comment by chrisdembia** [comment]
3.0.0 is the minimum version. 2.4.1 can open the ipynb, but 2.3.1 and earlier can't even open it

**Comment by moorepants** [comment]
Ok good to know. Maybe we can get it to work with 2.4+. I'd ideally like it to work with IPython 2 and 3.

**Comment by moorepants** [comment]
Oh, this is a different issue. One issue is whether we save our IPython notebooks as version 3.0 or 2.0. Ipython 2.4 has backported imports of Ipython 3.0 notebooks.

There are two issues:
1. What is the lowest version of IPython that can run the visualization (if the notebook version is correct).
2. Should we be saving all of our notebooks with IPython 2 so that both IPyhon 2 and 3 users can open them?

**Comment by chrisdembia** [comment]
Is there any reason why people are unable to access ipython 3?

**Comment by moorepants** [comment]
Probably not. I've just been trying to keep PyDy working with older dependencies. IPython 3 is relatively new. Pinning to very specific versions of programs may be ok. The main issue arises when you want to use PyDy along with other programs that may not support newer versions etc. In general, to help minimize the dependency hell issue, I've been trying to support a range of versions. numpy, scipy, sympy, cython etc are relatively stable across versions so we are supporting as far back as what is on Ubuntu 12.04 (travis machines). IPython, on the other hand, is jumping through major version numbers pretty rapidly.

One solution is to make IPython and optional dep and require > 3.0. If it is optional instead of required I don't mind it being stricter. Thoughts?

**Comment by moorepants** [comment]
@pydy/pydy-developers Question: Should we require IPython 3.0 or try to support IPython >= 2.0?

**Comment by moorepants** [comment]
FYI, it seems IPython is treated as optional in `scene.py`.

**Comment by moorepants** [comment]
@sahilshekhawat Is going to spend a little time to see if we can support IPython 2.4+. If it takes too much time we are going to only support IPython 3.0+ for this release.

**Comment by oliverlee** [comment]
3.0

**Comment by moorepants** [comment]
Ok, Python 3.0 will be the minimum we support for PyDy 0.3.0, see #235.
