### ISSUE TITLE
Scene.create_static_html() may be useless now.

### ISSUE THREAD

**Issue by moorepants** [pydy/pydy#156]
Previously you could export all of the html/css/js files to a directory and simply open up the index.html file in a web browser to interact with the visualization. Now that doesn't seem to be the case and a server is required due to AJAX?

We need to either update the docs explaining how to use the static files or make this work again.

**Comment by sahilshekhawat** [comment]
Yes, running AJAX do need a server. We can replace ``Scene.create_static_html()`` with a server call like ``Scene.start_server()``? I don't think we can make it work again with AJAX.

**Comment by moorepants** [comment]
I think there already is a method to start the server.

**Comment by tarzzz** [comment]
@sahilshekhawat `Scene.display()` fires a server on its own. 
@moorepants We cannot remove `create_static_html()` since other methods have a dependency on it.
We need to copy files to the cwd to make the server fetch the js files. It is being accomplished by `create_static_html()`.

**Comment by moorepants** [comment]
We need to have explanation in the documentation somewhere that shows how you can use the outputs of create_static_html and that it requires a server of some sort, either started from python or some other way.
