### ISSUE TITLE
Solve dynamic and kinematic odes separately.

### ISSUE THREAD

**Issue by moorepants** [pydy/pydy#16]
_Issue by **[moorepants](https://github.com/moorepants)** from Sunday Mar 30, 2014 at 03:19 GMT_
_Originally opened as https://github.com/pydy/pydy-code-gen/issues/25_

----

Right now the lazy thing is done: sovle(M, f) where M is the full mass matrix (for dynamical and kinematical equations of motion).

**Comment by moorepants** [comment]
Addressed in PR #113.

**Comment by jcrist** [comment]
Closed by #113
