### ISSUE TITLE
Setup Travis testing with more testing options

### ISSUE THREAD

**Issue by moorepants** [pydy/pydy#160]
I think we need these combinations:

1. Python 2.7 + lowest version of all deps we support (including optional deps).
2. Python 2.7 + lowest version of all deps we support (without optional deps).
3. Python 2.7 + SymPy master + latest version of deps.

We only have 1 right now.

Also, we could run the generation method benchmark in one of these.

**Comment by oliverlee** [comment]
3 is handled here: https://github.com/pydy/pydy/pull/231

**Comment by moorepants** [comment]
Now that we are using conda for testing, we need a few updates to the .travis.yml:

- [ ] Install Theano
