### ISSUE TITLE
Benchmarks are broken in master

### ISSUE THREAD

**Issue by sahilshekhawat** [pydy/pydy#164]
There is an UnboundLocalError when I ran benchmarks
```
Pendulum with 1 links.
======================
The derivation took 0.12791 seconds.

Traceback (most recent call last):
  File "bin/benchmark_pydy_code_gen.py", line 118, in <module>
    run_benchmark(args.max_num_links, args.num_time_steps)
  File "bin/benchmark_pydy_code_gen.py", line 49, in run_benchmark
    x0 = hstack((0, pi / 2 * ones(len(results[3]) - 1), 1e-3 *
UnboundLocalError: local variable 'results' referenced before assignment
```
I think while we fix this, we should remove it from README.

**Comment by moorepants** [comment]
We should probably run this on Travis. I get the same error on my machine.

**Comment by moorepants** [comment]
This commit seems to have introduced the error: https://github.com/pydy/pydy/commit/b1ff8495193e33975f48f3cbf7d412e7c2d42140#diff-eeabeda503d6c15fbf56d6bbe38f4459
