### ISSUE TITLE
Create a PyDy org on binstar and release PyDy there.

### ISSUE THREAD

**Issue by moorepants** [pydy/pydy#170]
This would allow simple installation using conda.

- [x] Create 0.2.1 conda recipe.
- [x] Create PyDy binstar org.
- [x] Upload 0.2.1 binaries.
- [ ] Create 0.3.0 recipe.
- [ ] Upload 0.3.0 binaries.

**Comment by sahilshekhawat** [comment]
Can we close this one now?

**Comment by moorepants** [comment]
Let's leave it open until we make the 0.3.0 release.

**Comment by sahilshekhawat** [comment]
This can be closed now.
