### ISSUE TITLE
Make sure all examples run before releasing 0.3.0.

### ISSUE THREAD

**Issue by moorepants** [pydy/pydy#178]
We need to get in the habit of running all of the examples before each release.

**Comment by chrisdembia** [comment]
I can try for this.

**Comment by moorepants** [comment]
Ok, thanks.

**Comment by moorepants** [comment]
Would you mind making a list of the examples here and let us know which ones have visualizations and which ones don't? Actually I would be nice to know whether each example meets these criteria: https://github.com/pydy/pydy/blob/master/CONTRIBUTING.rst#example. Then we can go through each one to update at some point in the future.

**Comment by chrisdembia** [comment]
- babyboot
  - [x] Runs without any exceptions or errors.
  - [ ] A figure (preferrably SVG) has been added for the example.
  - [ ] The required versions of all dependencies have been noted. (For
  notebooks, the [version information
  extension](https://github.com/jrjohansson/version_information) is helpful
  for this.)
  - [ ] A `run.py` file that executes the example is included.
- body_with_arm
  - [x] Runs without any exceptions or errors.
  - [ ] A figure (preferrably SVG) has been added for the example.
  - [ ] The required versions of all dependencies have been noted. (For
  notebooks, the [version information
  extension](https://github.com/jrjohansson/version_information) is helpful
  for this.)
  - [ ] A `run.py` file that executes the example is included.
- chaos_pendulum
  - [x] Runs without any exceptions or errors.
  - [x] A figure (preferrably SVG) has been added for the example.
  - [ ] The required versions of all dependencies have been noted. (For
  notebooks, the [version information
  extension](https://github.com/jrjohansson/version_information) is helpful
  for this.)
  - [ ] A `run.py` file that executes the example is included.
- differential_drive
  - [x] Runs without any exceptions or errors.
  - [x] A figure (preferrably SVG) has been added for the example.
  - [ ] The required versions of all dependencies have been noted. (For
  notebooks, the [version information
  extension](https://github.com/jrjohansson/version_information) is helpful
  for this.)
  - [ ] A `run.py` file that executes the example is included.
- double_pendulum TODO
- inertia_of_torus
  - [x] Runs without any exceptions or errors.
  - [ ] A figure (preferrably SVG) has been added for the example.
  - [ ] The required versions of all dependencies have been noted. (For
  notebooks, the [version information
  extension](https://github.com/jrjohansson/version_information) is helpful
  for this.)
  - [ ] A `run.py` file that executes the example is included.
- numpy_scipy
  - [ ] Runs without any exceptions or errors. **but it doesn't seem to be intended to run out of box**
  - [ ] A figure (preferrably SVG) has been added for the example.
  - [ ] The required versions of all dependencies have been noted. (For
  notebooks, the [version information
  extension](https://github.com/jrjohansson/version_information) is helpful
  for this.)
  - [ ] A `run.py` file that executes the example is included.
- mass_spring_damper TODO
- npendulum TODO
- parallel-execution
  - [ ] Runs without any exceptions or errors. **joblib required to run one of the files; multiprocessing works**
  - [ ] A figure (preferrably SVG) has been added for the example.
  - [ ] The required versions of all dependencies have been noted. (For
  notebooks, the [version information
  extension](https://github.com/jrjohansson/version_information) is helpful
  for this.)
  - [ ] A `run.py` file that executes the example is included.
- rattleback TODO
- rollingdisc
  - [ ] Runs without any exceptions or errors. ** rollingdisc.py is fine, rollingdisc_nonminimal.py fails**
  - [ ] A figure (preferrably SVG) has been added for the example.
  - [ ] The required versions of all dependencies have been noted. (For
  notebooks, the [version information
  extension](https://github.com/jrjohansson/version_information) is helpful
  for this.)
  - [ ] A `run.py` file that executes the example is included.
- sliding_ladder
  - [ ] Runs without any exceptions or errors. **doens't import anything**
  - [x] A figure (preferrably SVG) has been added for the example.
  - [ ] The required versions of all dependencies have been noted. (For
  notebooks, the [version information
  extension](https://github.com/jrjohansson/version_information) is helpful
  for this.)
  - [ ] A `run.py` file that executes the example is included.
- three_link_conical_pendulum
  - [ ] Runs without any exceptions or errors. **doens't import anything**
  - [x] A figure (preferrably SVG) has been added for the example.
  - [ ] The required versions of all dependencies have been noted. (For
  notebooks, the [version information
  extension](https://github.com/jrjohansson/version_information) is helpful
  for this.)
  - [ ] A `run.py` file that executes the example is included.
- tutorials TODO

**Comment by chrisdembia** [comment]
done

**Comment by moorepants** [comment]
Awesome! Thanks for doing this.

We can try to fix them up. I'll  see if I can get some others to help.

**Comment by tarzzz** [comment]
Rolling Disc (Non minimal example) works for me. Updating the same on the checklist above.

**Comment by moorepants** [comment]
Ok, we have at least gotten all of the examples to run in master. I'm going to close this issue but we need to open a new issue for each example to get them in shape. We will work on this at the SciPy sprints.
