### ISSUE TITLE
Visualization examples do not work sometimes

### ISSUE THREAD

**Issue by sahilshekhawat** [pydy/pydy#182]
This bug is consistence in examples like double pendulum,  three link conical pendulum etc. Sometimes examples do not work and I am yet to find the reason (but they mostly happen when there is no file from previous run). Instead of the visualization of the example they shows the visualization as in the image below
![part1](https://cloud.githubusercontent.com/assets/5890452/7806484/13a6cbaa-039f-11e5-9cb2-649148f94db4.png)

**Comment by sahilshekhawat** [comment]
The correct visualization is shown on reload.

**Comment by sahilshekhawat** [comment]
Reloading after sometime works though!

**Comment by sahilshekhawat** [comment]
I think this is responsible [L23](https://github.com/pydy/pydy/blob/master/pydy/viz/static/js/dyviz/parser.js#L23)
As, the call is not completed before Scene and thus, json file is not loaded.

**Comment by moorepants** [comment]
@sahilshekhawat Do you still see this problem? I haven't encountered it in a while.

**Comment by sahilshekhawat** [comment]
Yeah! I just tried it and it works right away.

**Comment by moorepants** [comment]
Ok, let's close this. We can reopen it if we come across this again.
