### ISSUE TITLE
Editing materials via the GUI causes the camera to freeze and the object size to change

### ISSUE THREAD

**Issue by moorepants** [pydy/pydy#187]
To reproduce:

1. Run `python visualize.py` in the `three_link_conical_pendulum` example.
2. Open link in browser.
3. Click "Edit Objects" and select the first cylinder.
4. Change the material to an option other than default and click "Apply".

The object changes to the material, the object size grows, and the trackballcontrols lock.

**Comment by sahilshekhawat** [comment]
I have fixed this in #185

**Comment by sahilshekhawat** [comment]
The only thing remaining is object size and its reason is that it is defined in simulation.json and when we do edit object it adds custom camera. Its not a bug. Its just how we intend it to behave.
Can you please tell me how we intend it to be?

**Comment by moorepants** [comment]
This is looking good. I tested out the three link pendulum. The only thing that is odd is that when you press play, the camera resets to some view other than the one you currently have defined with the mouse controls. This also happens when you press "apply" in the object editing dialog. In both of those cases the camera view should remain as set by the user through the gui.
