### ISSUE TITLE
Notebook viz does not function completely in IPython 2

### ISSUE THREAD

**Issue by moorepants** [pydy/pydy#198]
I tried out the double pendulum notebook example with IPython 2.4.1 and:
- The animation slider does not seem to work. It doesn't move when play is pressed and can't be moved manually.
- It does not seem like the "rerun simulation" button is working.

We need to also determine how far back in the 2 series of IPython we can go back. My guess is that it may not work with IPython 2.0.

**Comment by sahilshekhawat** [comment]
Animation slider works perfectly with the latest master but there are other issues
1. mathjax is not working, constants have ``$`` with them.
2. Rerun simulation still doesn't work.
3. Edit objects and close dialog, which should be above canvas are now displayed in a separate place. This is very weird. 
![pydy-ipython4](https://cloud.githubusercontent.com/assets/5890452/8149466/da958912-12e1-11e5-9a62-ca3cc3c8ef85.png)

**Comment by sahilshekhawat** [comment]
Also, even when the visualization is rendered, notebook is still shown as busy. It seems like there is a loop of something similar which is not completed and thus, results in above problems.

**Comment by moorepants** [comment]
@sahilshekhawat Seems like people just want to support 3.0+, see #155. Maybe we should do that.

**Comment by moorepants** [comment]
But it looks like you are close there. The MathJax rendering may be a simple fix. And maybe IPython 2 has a different boostrap lib that is causing the other issues.

But for the rerun, maybe we can just disable the rerun for IPython 2. But we can likely get that working too.

How much more work do you think it will take?

**Comment by moorepants** [comment]
@sahilshekhawat Let's drop support fro IPython 2. We can move the code for Python 2 in a new PR if we want to try and support it in a later release, but I think for now we need to simply require IPython 3 as an optional dependency. Sorry for leading you down this course, but it was worth a shot.

**Comment by moorepants** [comment]
I'm moving this issue from the 0.3.0 milestone in favor of issue #235.

**Comment by oliverlee** [comment]
We are not supporting IPython 2.

**Comment by moorepants** [comment]
We dropped IPython 2 support with the 0.3.0 release because we couldn't get it working in time. We could likely support IPython 2 but it may not be worth it at this point. I'm not sure what is in Ubuntu 14.04 as far as IPython goes.

**Comment by moorepants** [comment]
If we are supporting trusty this is bad news: http://packages.ubuntu.com/trusty/ipython

**Comment by oliverlee** [comment]
Looks like I shouldn't have closed this.

**Comment by moorepants** [comment]
Supporting IPython 1 is impossible because there is no widget functionality. But we could probably support IPython 2. It's probably not worth the trouble though.

**Comment by oliverlee** [comment]
Okay we should close this issue unless someone is willing to work on it.
