### ISSUE TITLE
The notebook visualization may prevent you from restarting the kernel

### ISSUE THREAD

**Issue by moorepants** [pydy/pydy#203]
I ran the mass spring damper example in PR #97 and if I "Run All" and then "Kernel>Restart" the notebook just hung in a grey screen. I had to close the browser tab and open a the notebook again to bring it back to life. There also seems to be odd behavior when "close and halt" is selected in a notebook with a viz present.

**Comment by moorepants** [comment]
@sahilshekhawat Any idea why this might be? Have you experienced it. I can't pinpoint how to reproduce it perfectly but it happens to me often.

**Comment by sahilshekhawat** [comment]
Yes it does,  notebook just hangs and turns dark.

**Comment by moorepants** [comment]
If you click the grey x on the visualization wigdet before trying to restart all is fine. So the widget somehow locks things up.

**Comment by moorepants** [comment]
This seems reproducible to me:

1. Open the mass_spring_damper notebook.
2. Click "Cell>Run All"
3. Once the notebook completely renders (you may need to type "y" at the viz), click "Kernel>Restart".

The notebook locks up.

To prevent this you can close the widget at the bottom using the little "x" in the upper left corner of the widget.

**Comment by moorepants** [comment]
I will ask about this on the IPython mailing list.
