### ISSUE TITLE
Displaying the visualizer distorts the ipython header, etc.

### ISSUE THREAD

**Issue by chrisdembia** [pydy/pydy#209]
calling display_ipython() causes the header to get unnecessary whitespace.

python 2.7.6 ipython 3.0.0

before
![screenshot from 2015-06-08 23 25 06](https://cloud.githubusercontent.com/assets/846001/8051878/6d0948ac-0e36-11e5-93fc-8532e7a86f9f.png)

after
![screenshot from 2015-06-08 23 28 49](https://cloud.githubusercontent.com/assets/846001/8051894/86d1fe5a-0e36-11e5-8ba6-bbb7babd1334.png)

**Comment by sahilshekhawat** [comment]
Its due to bootstrap. It changes the header after visualization.

**Comment by moorepants** [comment]
But it shouldn't. Do you know how to prevent it?

**Comment by sahilshekhawat** [comment]
Yes,  fixing it in #183

**Comment by sahilshekhawat** [comment]
I tried but ``@import`` is not working, nor is scoped css in HTMLWidget.

**Comment by moorepants** [comment]
Ok, we'll look into it. It isn't a deal breaker.

**Comment by moorepants** [comment]
Sahil says that that IPython widgets do not support  scoped css and @import doesn't work. He is going to ask on the IPython list about a work around.

**Comment by sahilshekhawat** [comment]
I asked them and they say
> Yes we are aware that css leaks. We plan on prefixing all ipython css, but it will take a while. Note that notebook css already use bootstrap so you shouldn't need to inject your own.

So, I think we can just get away by removing bootstrap. I am trying it right now.

**Comment by moorepants** [comment]
But we also have the `.display()` method, so we need boostrap for that.

**Comment by sahilshekhawat** [comment]
Its working! I just removed import of bootstrap from index_ipython and it works.
