### ISSUE TITLE
Move Mesh Shape into a WIP PR.

### ISSUE THREAD

**Issue by moorepants** [pydy/pydy#21]
_Issue by **[tarzzz](https://github.com/tarzzz)** from Tuesday Sep 17, 2013 at 07:50 GMT_
_Originally opened as https://github.com/pydy/pydy-viz/issues/61_

----

Implement mesh shape in addFrames

**Comment by moorepants** [comment]
@tarzzz If this doesn't work we should remove the Mesh shape from the code and move it to a WIP PR.

**Comment by tarzzz** [comment]
We can move the entire mesh setup into a WIP PR, since it would require some effort to get MeshShape working.

**Comment by moorepants** [comment]
Yes, I think that needs to be done. Sounds like a plan.

**Comment by tarzzz** [comment]
Quick question @moorepants : Do you want me to entirely remove the Mesh related code (both Python and JS) and move it to a PR? or simply add a "NotImplementedError" wherever it exists.?

**Comment by moorepants** [comment]
If the mesh code does not function I don't think it belongs in master. I doubt anyone has actually used it if it doesn't function so there is no reason to add in NotImplementedErrors. We will just pretend it wasn't there in the first place.

**Comment by tarzzz** [comment]
That seems fine. I will remove it all, and create a PR for the same

**Comment by tarzzz** [comment]
https://github.com/pydy/pydy/pull/158 Fixes this issue..
