### ISSUE TITLE
Clean exit of server

### ISSUE THREAD

**Issue by sahilshekhawat** [pydy/pydy#232]
I have few samples of how we can do this: [HERE](https://gist.github.com/sahilshekhawat/a2e79a8df8ce4f31ff4e) and [HERE](https://gist.github.com/sahilshekhawat/93d333af699b82c8bda7)
Both of them fails sometimes because handle_request processes thread in another thread and thus I cannot catch the keyboard interrupt. This fails only when a request is being processing.

**Comment by moorepants** [comment]
If this needs to be fixed for 0.3.0 please at the milestone.

**Comment by tarzzz** [comment]
That seems a good way, @sahilshekhawat you can raise a PR for the same!

**Comment by sahilshekhawat** [comment]
But it still raises KeyBoardInterrupt when a request is being processed. To fix this we need to create our custom subclasses of BaseHTTPServer and SimpleHTTPRequestHandler. I will try to fix it as soon as other more important bugs can be fixed for the release.

**Comment by moorepants** [comment]
@oliverlee Mentioned that he has a working example of a clean exit. He gave me this link:

https://github.com/oliverlee/bikesim/commit/18ce0f443c73e2efe530821927dd4f5cb0b973d5

But I haven't looked closely yet to find the server exit code.

**Comment by oliverlee** [comment]
You can run the server in a separate thread from the main thread. In the main thread, you can catch a KeyboardException and signal the server thread. The signal thread periodically checks if it should terminate, and if so, performs your shutdown/cleanup actions. At this point, the server thread function finishes and the server thread terminates. You can signal a thread easily with threading.Event().

Also please try to use the print function so that it is easier to maintain compatibility with Python 3.

**Comment by moorepants** [comment]
> Also please try to use the print function so that it is easier to maintain compatibility with Python 3.

The new Travis tests will ensure this for the future.

**Comment by moorepants** [comment]
@sahilshekhawat Does this need to be in the 0.3.0 milestone?

**Comment by sahilshekhawat** [comment]
We should do this, but I don't know if we have enough time.

**Comment by moorepants** [comment]
If it is critical to have a functioning app, we can ensure that it gets in. I don't really understand the bug yet? I haven't experienced it. How do you reproduce it?

**Comment by sahilshekhawat** [comment]
It's not a bug.  It's just to hide keyboard interrupt from users on server
exit.

**Comment by moorepants** [comment]
Can you explain in steps how to reproduce this behavior? I still don't understand what is going on.

Also can you please give your opinion on whether this is critical for the 0.3.0 release? If it is not a bug, I'm guessing it is not critical.

**Comment by moorepants** [comment]
@sahilshekhawat Have you addressed this in #196?

**Comment by sahilshekhawat** [comment]
Yes, I have addressed it there.
 when we close our server it raises KeyboardInterrupt error and this issue is to show something like "Do you really want to exit [y]/n?
