### ISSUE TITLE
The visualization canvas is not bounded by the notebook width on large resolution screens.

### ISSUE THREAD

**Issue by moorepants** [pydy/pydy#236]
![selection_099](https://cloud.githubusercontent.com/assets/276007/8177451/bc6db472-13b9-11e5-950f-96538a5090ce.png)

**Comment by oliverlee** [comment]
What do you mean large resolution? This looks fine on my retina MBP.

**Comment by moorepants** [comment]
I have a 22" monitor at 1680 x 1050 and this is running under Firefox. If I make the Firefox window smaller it eventually is bounded by the edges of the notebook and sticks to the width of the notebook, bu tat some width it will once again stay the min canvas width and exceed the notebook bound.

The screenshot above is with Firefox expanded to fill the screen width.

**Comment by oliverlee** [comment]
I don't think there's anything you can do. At some point the browser will be too small to display the canvas. This occurred after reducing my browser width to about a quarter of my screen width on OSX Yosemite with Chrome.

**Comment by moorepants** [comment]
What we were hoping to achieve was that the canvas has a minimum size. If you make the window smaller than that minimum size it stays that size and you have to scroll your browser. But if you make your window larger the canvas should fill the space. This works with the plain `.display()` method really well. But inside the notebook, there is a fixed max width of the notebook. The canvas should be responsive inside the notebook and always fill the space, unless you make the window smaller than the canvas's minimum size. I think our css/js just isn't playing well inside the IPython widget for this to work correctly. Does that make sense?

**Comment by moorepants** [comment]
It sounds like your system has the correct behavior. Maybe this is only in Firefox?

**Comment by oliverlee** [comment]
Makes sense. Same issue on my end.
