### ISSUE TITLE
Viz json files need to have valid filenames for all OSs.

### ISSUE THREAD

**Issue by moorepants** [pydy/pydy#238]
Colons are not supported in Windows!

**Comment by moorepants** [comment]
@sahilshekhawat We need to take care of this along with PR #196

**Comment by sahilshekhawat** [comment]
Yeah, it will be easy to integrate it with that. Thanks

**Comment by moorepants** [comment]
This is addressed in #240.

**Comment by moorepants** [comment]
Now addressed in #242.
