### ISSUE TITLE
Delete all merged branches on Github

### ISSUE THREAD

**Issue by moorepants** [pydy/pydy#24]
- [ ] Deal with remaining branches in this repo that have unmerged commits.
- [ ] Add note to contributing that recommends using `git://` to prevent pushing to the main repo.

_Issue by **[moorepants](https://github.com/moorepants)** from Monday Sep 23, 2013 at 15:02 GMT_
_Originally opened as https://github.com/pydy/pydy-viz/issues/77_

---

There are a ton of branches in the repo. I think many of them have been merged. All of the branches that have all commits in master should be deleted:

```
git push origin :<branch name>
```

Be sure to only delete ones that have been fully merged or are sure to not be used.

**Comment by moorepants** [comment]
Cleaned up a bunch of these. The remaining list contains ones that are tied to open PRs and several that have unmerged commits. We can revisit after we go through some to the PRs. We should also stop pushing lots of branches to the main repo. In SymPy we recommend that you set the upstream branch to:
```
[remote "upstream"]
	url = git://github.com/sympy/sympy.git
	fetch = +refs/heads/*:refs/remotes/origin/*
```
that way you can't accidentally push branches or anything to master. Best just push to your fork.

**Comment by oliverlee** [comment]
I set master as a protected branch. No one can push to it now without first pushing to another branch and  passing travis tests.

**Comment by moorepants** [comment]
cool, thanks

**Comment by oliverlee** [comment]
Should we remove all the closed branches? I thought we were creating branches on our forks of pydy and submitting pull requests.

**Comment by moorepants** [comment]
We pushed directly to this repo in the past and at some point switched to the model you quote once we got more contributions, so there are some lingering branches here that may or may not be tied to open PRs.

**Comment by moorepants** [comment]
Yes, any branches that have been merge or definitely abandoned (no future use) should be deleted.

**Comment by oliverlee** [comment]
@tarzzz @chrisdembia please remove closed or abandoned branches

**Comment by marwahaha** [comment]
Looks good now!

![image](https://user-images.githubusercontent.com/2541209/44943211-48dda980-ad77-11e8-8de5-da757a6881d8.png)
