### ISSUE TITLE
Scene.display_ipython() does not render the canvas in Firefox 38 on Windows 7

### ISSUE THREAD

**Issue by moorepants** [pydy/pydy#248]

**Comment by oliverlee** [comment]
@moorepants can you check this (with a newer version of firefox) when you use windows this weekend?

**Comment by moorepants** [comment]
I just checked this again on Windows 7 with PyDy 0.3.0 and Firefox 38.0.5 and all seems to work fine.

**Comment by moorepants** [comment]
Also works with Firefox 40.0.3 and 43.0.1.

**Comment by extraymond** [comment]
I'm on firefox nightly with linux (ubuntu 15.10 64bit) and it's not working again.
My pydy version is 0.3.1.
It worked fine 2 weeks ago.

**Comment by oliverlee** [comment]
@extraymond Can you provide the nightly build number and check if webgl is supported/enabled in about:config?
