### ISSUE TITLE
The slider time value does not match the actual time of the simulation

### ISSUE THREAD

**Issue by moorepants** [pydy/pydy#253]
It doesn't seem like the JS slide is even aware of the time value that is use in the simulation.

**Comment by oliverlee** [comment]
It just uses `frames_per_second` to slow down or speed up the simulation: https://github.com/pydy/pydy/blob/df1e7fe682bba319be8de84550d9abb376bc4cb2/pydy/viz/scene.py#L413-L414

**Comment by oliverlee** [comment]
Fixed here: https://github.com/pydy/pydy/commit/b5edaf401df648fa889de9e6e292148f78ae3619
