### ISSUE TITLE
Animation speed

### ISSUE THREAD

**Issue by moorepants** [pydy/pydy#26]
_Issue by **[moorepants](https://github.com/moorepants)** from Saturday Jan 18, 2014 at 21:30 GMT_
_Originally opened as https://github.com/pydy/pydy-viz/issues/81_

----

The animation currently runs as some framerate. It is not clear what frame rate this is. Ideally, we'd want it to run as close to real time as possible, i.e. if I have a time vector in seconds from 0 to 10 seconds, then the animation should last ten seconds in real time. It would be also nice to speed up, slow down the framerate with a JS gui slider, checkbox, or button.

**Comment by moorepants** [comment]
@tarzzz What is the status of this now that you have a new GUI? I know there is a slider for the frames.

**Comment by tarzzz** [comment]
We have a slider to move to a specific location in the animation, but no way to control the speed the animation runs (fast or slow). I guess we already had a discussion on the same, and we decided to use slider to move to specific frames, rather than slowing/pacing the animation. Can be closed.

**Comment by moorepants** [comment]
Ok, let's close this.
