### ISSUE TITLE
Ensure that PyDy works with IPython 4.0 (Jupyter)

### ISSUE THREAD

**Issue by moorepants** [pydy/pydy#261]
IPython has been spit up into multiple packages (both IPython and Jupyter packages). We need to make sure PyDy works with 4.0+.

**Comment by moorepants** [comment]
The mass_spring_damper example does not run in IPython 4 (Python 2.7) and this is the traceback:

![selection_014](https://cloud.githubusercontent.com/assets/276007/10271809/4c8cebd2-6acb-11e5-9d01-e9bc3e78ade4.png)

**Comment by moorepants** [comment]
The IPython widgets are now in a new separate package called "ipywidgets". If you install that, things work mostly as expected `conda install ipywidgets`. Notice that the rerun button is very wide now:
![selection_015](https://cloud.githubusercontent.com/assets/276007/10271857/1e13a2a4-6acc-11e5-94dc-550f9ebb1cb6.png)

So we need to make `ipywidgets` a dependency for IPython 4+ to fix this error.

**Comment by tarzzz** [comment]
Jupyter comes installed with ipywidgets ( and all the other components which were earlier the part of core IPython). So there is no need to make those individual components as dependency. With Jupyter, they will be automatically installed. Although we do need to update our code to be Jupyter-compatible.

We can move the discussion to make code Jupyter-compatible to this PR:
https://github.com/pydy/pydy/pull/268

**Comment by moorepants** [comment]
When I conda install ipython-notebook, ipywidgets is not installed automatically.

**Comment by moorepants** [comment]
I just reported this issue to anaconda: https://github.com/ContinuumIO/anaconda-issues/issues/470

**Comment by moorepants** [comment]
The ipywidgets missing was acutally an upstream issue:

https://github.com/ipython/ipython/issues/8905

PyDy will have to depend on the patched version of IPython 4.0 or we can explicitly declare ipywidgets as a dep.

**Comment by moorepants** [comment]
I made a note about this in #90 to the README.

I'll also update the conda packages to correctly install ipywidgets once we make the release.

**Comment by moorepants** [comment]
This works in IPython 4.0 now.
