### ISSUE TITLE
C code generation line break issue

### ISSUE THREAD

**Issue by blumenta** [pydy/pydy#263]
Hello, while using CythonMatrixGenerator and CMatrixGenerator I stumbled upon the following issue:
the generated C code appears to have some undesirable line breaks which render the code uncompilable. For example, this generated statement

double pydy_2382 = (1.0L/4.0L)pydy_1930pydy_203pydy_204pydy_2339pydy_2
95pydy_345*pydy_60;

yields the following gcc error:

error: expected ‘,’ or ‘;’ before numeric constant
95pydy_345pydy_60;

Of course there shouldn't be a line break in the middle of the variable name pydy_295. That happens when attempting to compile the C code on my own. When I try using the CythonMatrixGenerator.compile() method, the Exception('Failed to compile and import Cython module.') is raised, I guess because of the same issue.
For now I managed to correct the generated c code manually since there are only 2 occurrences of this error, but maybe this is an issue that could be easily fixed in pydy.

Thanks in advance,

Alejandro

**Comment by oliverlee** [comment]
Thanks for reporting the issue. Can you give an example that will reproduce this error?

**Comment by oliverlee** [comment]
This can probably be solved by setting `TextWrapper.break_long_words` to `False` but I haven't been able to reproduce the bug and am not sure why it occurs in the first place as the text in the less than the set textwidth: https://github.com/pydy/pydy/blob/8ded40cb0d0c48daf21a53229b7669900be3320f/pydy/utils.py#L35-L48

**Comment by moorepants** [comment]
@blumenta Please provide an small example that demonstrates this bug, otherwise it is difficult for us to track it down.

**Comment by blumenta** [comment]
Hi, sorry I have been trying to reproduce the bug in a small example but haven't been able to do so. It occurs in the code I'm working on, but I'm kind of in a bind because I am not currently allowed to distribute it. Maybe I could save the problematic expression in a text file directly and then have a script that loads it and runs the C code generator on it. I'll get back to you

**Comment by oliverlee** [comment]
Thanks for the update. If you can save the expression to the text file that
would be great. If not, we can try writing a patch and having you test it
locally so let us know when you have a chance.

**Comment by blumenta** [comment]
Hi, you will find attached source code that reproduces the bug. I saved the
problematic expression in a file 'dMdx.txt', the script 'bug.py' loads this
expression and prints the generated C code to the files
'pydy_codegen_c.{c,h}', these can be directly compiled with gcc using the
Makefile also included in the tar ball. Compilation fails because of the
above mentioned issue.
Thank you for your patience, I hadn't had any time lately to deal with this
issue because of a lot of teaching duties.
I hope this will be helpful, kind regards,

Alejandro

2015-10-09 12:15 GMT+02:00 Oliver Lee <notifications@github.com>:

> Thanks for the update. If you can save the expression to the text file that
> would be great. If not, we can try writing a patch and having you test it
> locally so let us know when you have a chance.

**Comment by oliverlee** [comment]
I think you forgot to attach the files (or maybe you can't do so by email).

**Comment by moorepants** [comment]
@blumenta Please email to the pydy list (or our personal email address) or make a gist or something with the code.

**Comment by oliverlee** [comment]
Text wrap doesn't know that it can insert newlines after multiplication or division operators. We see output like this:

```python
    double pydy_1462 = (1.0L/8.0L)*input_1[1]*pydy_1317*pydy_25*pydy_29*pydy_41
    1*pydy_63*pydy_78*pydy_99;
```

and this:

```python
    double pydy_1462 = (1.0L/8.0L)*input_1[1]*pydy_1317*pydy_25*pydy_29*pydy_41
    1*pydy_63*pydy_78*pydy_99;
```

**Comment by oliverlee** [comment]
Fixed here: https://github.com/pydy/pydy/pull/292

**Comment by moorepants** [comment]
@blumenta Can you verify that this patch fixes things for you?

**Comment by blumenta** [comment]
Hi, I just tested it and it works perfectly, nice work.

2015-10-20 19:35 GMT+02:00 Jason K. Moore <notifications@github.com>:
