### ISSUE TITLE
Bump lowest supported dependency versions up to newer versions

### ISSUE THREAD

**Issue by moorepants** [pydy/pydy#271]
> NumPy 1.7 and SciPy 0.11 were released Feb 2013 and Sept 2012 respectively. NumPy 1.9 and Scipy 0.14 were released in Sept and May 2014. I suggest we drop support for earlier versions.

@oliverlee, that's sounds reasonable. I've been keeping the older NumPy/SciPy versions around because, as far as I know, we use very minimal functionality from those dependencies and there aren't compatibility issues, even back to earlier versions than these. Theano is an optional dependency and it seems odd to force the upgrade for just it, which I'm not even sure is used much. The other issue is that we don't put bounds on these deps in sympy for lambdify. The "real" issue would be specifying these at the sympy level and then we would just follow suite.

The other reality is to know whether people use pydy with the system installed packages from various linux distros. I wasn't long ago when I used a combination of system packages and pip installed packages (i.e. before my switch to conda). If people use conda we could literally always support the latest version but if we want to support the system packages, for example, those that are in the LTS debain/ubuntu releases, then we need to be more careful. Not everyone has switched to conda yet. I had originally been testing against whatever version was in the Ubuntu 12.04 release that Travis uses which was released in April 2012 and is supported until April 2017.

Anyways, that was my reasoning. This was all in place to relieve installation and compatibility issues one would see when not using conda, which is still a great number of people. The other option would to simply tell people to use conda if they want to use this package.

**Comment by moorepants** [comment]
Versions in Ubuntu 14.04 Trusty:
- NumPy 1.8.1
- SciPy 13.3
- matplotlib 1.3.1
- cython 0.20.1
- theano: no debian package
- sympy 0.7.4.1

**Comment by oliverlee** [comment]
Certainly it would be easier if everyone switches to conda. However, I still have to use pip to install some packages (e.g.  theano):

```
oliverlee@canopus:~$ conda search theano
Fetching package metadata: ....
oliverlee@canopus:~$ 
```

And we also need something that we can test, hopefully without needing to spend much time maintaining it ourselves, which conda should provide. If we support only the most recent Ubuntu LTS, that sounds reasonable. We could then add another category to the build matrix without theano.

I think we should avoid telling people to use conda if they want to use this package. Incompatibility issues that crop up with conda still exist and are painful  to debug.

**Comment by moorepants** [comment]
Oh, yeah contiuum has built a theano package for mac is seems. Note that `conda search

We could build a mac theano package.

**Comment by oliverlee** [comment]
I've dropped the minimum dependency versions to match packages available in Ubuntu 14.04 in this PR: https://github.com/pydy/pydy/pull/282

Since we (you) need to build the packages, we might as well build them for Python 3 so we can also address this issue: https://github.com/pydy/pydy/issues/234

**Comment by moorepants** [comment]
I just pushed some min deps for Python 3.5 to our pydy channel. Hopefully that works.

**Comment by oliverlee** [comment]
We'll also need the min deps for Python 2.7, 3.3, and 3.4.

**Comment by moorepants** [comment]
Ok, i'll work on them, but maybe not till tomorrow. I'll push all the recipes too. I think I'll make a pydy/conda-recipes repo with all the recipes for our channel.
