### ISSUE TITLE
Latex output does not work in mass spring damper example on OSX

### ISSUE THREAD

**Issue by oliverlee** [pydy/pydy#286]
I think this worked when I tested in Ubuntu 15.04.

I get this error when running the mass-spring-damper example when printing ```fr, frstar```: https://gist.github.com/oliverlee/d9f777211a4269ba7777

It works if pass in an option to init_vprinting:
```python
init_vprinting(use_latex='mathjax')
```

so I don't know if that is necessary or if I just have a package setup/install problem.
```
(dev)oliverlee@canopus:~$ conda search mathjax
Fetching package metadata: ....
mathjax                      2.2                      py35_0  defaults
                          .  2.2                      py34_0  defaults
                             2.2                      py33_0  defaults
                             2.2                      py27_0  defaults
                             2.2                      py26_0  defaults
```

and I've installed some version of mactex:
```
(dev)oliverlee@canopus:~$ latex --version
pdfTeX 3.14159265-2.6-1.40.16 (TeX Live 2015)
kpathsea version 6.2.1
Copyright 2015 Peter Breitenlohner (eTeX)/Han The Thanh (pdfTeX).
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Peter Breitenlohner (eTeX)/Han The Thanh (pdfTeX).
Compiled with libpng 1.6.17; using libpng 1.6.17
Compiled with zlib 1.2.8; using zlib 1.2.8
Compiled with xpdf version 3.04
```

**Comment by moorepants** [comment]
Yes, this is an issue we are working on over at sympy. See: 
https://github.com/sympy/sympy/pull/9976

**Comment by oliverlee** [comment]
Do we want to fix the example so it works or just wait for a fix from sympy?

**Comment by oliverlee** [comment]
Also that recently merge PR is not causing the problem for me.

```
(dev)oliverlee@canopus:~/repos/sympy$ git log --oneline | head -n1
a76b3fa Merge pull request #9856 from leosartaj/rf
```
My version of Sympy is set to this commit: https://github.com/sympy/sympy/commit/a76b3fa

**Comment by moorepants** [comment]
You can fix the example with `init_vprinting(use_latex='mathjax')`. That should work.

**Comment by moorepants** [comment]
The matrices in the example should render with mathjax, but they were rendering with pretty printing for me in that commit.
