### ISSUE TITLE
Verify no console output when generating python modules in Windows

### ISSUE THREAD

**Issue by oliverlee** [pydy/pydy#293]
Verify that PR: https://github.com/pydy/pydy/pull/291 does not print compilation warnings and errors on Windows.

**Comment by moorepants** [comment]
Cython does not run by default on Windows because there is no suitable compiler installed. It looks like a real pain in the rear to get Cython working on Windows, see:

https://github.com/cython/cython/wiki/CythonExtensionsOnWindows

**Comment by moorepants** [comment]
This is good. You can see it on the appveyor tests.
