### ISSUE TITLE
make _create_rhs_function cleaner

### ISSUE THREAD

**Issue by yashu-seth** [pydy/pydy#300]
We unfortunately support way too many ways to pass in extra arguments to the generated rhs function. The default behavior is to parse the arguments passed into the rhs function which can add a lot of computational overhead. So we allow the user to specify what type the extra args should be for both the constants and the specifieds. The constants can be None, 'array', or 'dictionary'. The specifieds can be None, 'array', 'function', or 'dictionary'. Thus we have 12 permutations of this "switch".

**Comment by yashu-seth** [comment]
@moorepants I think this can be implemented with lesser lines of code. Should I look into this?

**Comment by moorepants** [comment]
If you think you can improve it, sure. The reason it is like this is because these details play a big role in the execution speed of the right hand side and that we have this stuff at the Python level. Feel free to improve it but play close attention to the speed of execution.

**Comment by yashu-seth** [comment]
#301
