### ISSUE TITLE
We should be able to speed up the evaluation of the transformation matrices with this.

### ISSUE THREAD

**Issue by moorepants** [pydy/pydy#32]
_Issue by **[moorepants](https://github.com/moorepants)** from Sunday Jan 26, 2014 at 03:28 GMT_
_Originally opened as https://github.com/pydy/pydy-viz/issues/97_

----

See the end of this issue:

https://github.com/sympy/sympy/issues/2826

If you overwrite the ImmutableMatrix function with np.array, then you can use vectorized operations instead of a for loop.

**Comment by oliverlee** [comment]
In the method you suggest, constant entries in the transform result in a scalar being returned instead of a numpy ndarray. If a constant matrix entry is evaluated before a varying entry, the evaluation of the lambdified function fails. You can see this by setting ```mat_expr[0, 0] = 0``` in your example.

**Comment by oliverlee** [comment]
Resolved here: https://github.com/pydy/pydy/commit/42aae29ab26d0cbbbfd657c33f32bbd5dc53bb6f
