### ISSUE TITLE
Add more checks for times in System

### ISSUE THREAD

**Issue by yashu-seth** [pydy/pydy#321]

**Comment by yashu-seth** [comment]
@moorepants I found that there are not enough checks for the times input in the System class. Do you have any suggestions? I would like to work on it.

**Comment by moorepants** [comment]
I don't know what you mean by "checks". Maybe paste or reference some code that you are concerned about.

**Comment by yashu-seth** [comment]
```python
@times.setter
    def times(self, new_times):
        self._times = new_times

    def _check_times(self, times):
        """
        Very basic checking.
        TODO: add more checking
        """
        if len(times) == 0:
            raise TypeError("Times supplied should be in an array_like format.")
        return True
```

**Comment by moorepants** [comment]
Oh, I see. What other kinds of checks are needed?

**Comment by yashu-seth** [comment]
I think ```times``` list should be in ascending order and negative time should not be permitted. Do you have anything else in mind?

**Comment by moorepants** [comment]
That seems reasonable.
