### ISSUE TITLE
Move our contributing checklist to an issue template

### ISSUE THREAD

**Issue by moorepants** [pydy/pydy#329]
Github just introduced this new feature:

https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by jinankjain** [comment]
I would like to work on this.

By the issue what I understand is that you want to transform Contributing.rst to an issue template.
Am I right?

**Comment by moorepants** [comment]
Yes you can try it out. See how the new functionality works and see if you can have the checklists and such from CONTRIBUTING to work with this.

**Comment by jinankjain** [comment]
I was thinking of making a pull request template like this https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/ @moorepants Am I right ?

**Comment by moorepants** [comment]
One issue is that we have different checklists for different types of pull requests. I'm not sure how you can make that work.

**Comment by jinankjain** [comment]
@moorepants  I was thinking of making a format like as explained in example. 

It will have sections like:
1) Fixes #
2) Changes proposed in the pull request
3) tagging the admin of the repository

**Comment by moorepants** [comment]
That's all fine but we already have a template for different types of pull requests here:

https://github.com/pydy/pydy/blob/master/CONTRIBUTING.rst

We manually paste these checklists into each pull request based on what the PR is. So your template should be able to handle our current method to "templating" pull requests. If you want to add additional info that's ok to. We can discuss on the PR you make.

**Comment by sahilshekhawat** [comment]
Should we shift ``Contributing``, ``issue_template`` and ``pull_request_template`` to ``.github/``

**Comment by sahilshekhawat** [comment]
and we don't have an issue_template yet, right?
