### ISSUE TITLE
CSS broken for ``display_ipython()`` in the latest release.

### ISSUE THREAD

**Issue by sahilshekhawat** [pydy/pydy#341]
I think, it is already fixed. Can we release a patch or a minor release to fix this?
![pydy](https://cloud.githubusercontent.com/assets/5890452/13902960/acaa1d12-ee9e-11e5-9838-15611b1bf39b.png)

**Comment by moorepants** [comment]
It is fixed in master and will be included in 0.4.0. I wasn't planning a bugfix release.

**Comment by moorepants** [comment]
I'm closing this because it is already fixed. If you want to open an issue about releasing a bug fix release (0.3.2) then make a new issue with the list of bug fixes from master that should be included.
