### ISSUE TITLE
Not working across all browsers and OSs

### ISSUE THREAD

**Issue by moorepants** [pydy/pydy#36]
_Issue by **[moorepants](https://github.com/moorepants)** from Monday Feb 24, 2014 at 19:16 GMT_
_Originally opened as https://github.com/pydy/pydy-viz/issues/113_

----

We've found this by trying to run the notebooks in the pydy pycon tutorial.

One issue is that if you have a notebook open in a non-default system web browser then run `scene.display()` it tries to open a new tab in the default browser which may or may not be open.

Here are some notes:

Windows XP 32bit (in virtual box)
------------------------------------------
- Firefox 27.0.1 (set as default) the canvas does not load.
- Chrome Version 33.0.1750.117 m everything works.

Windows 7 64 bit (in virtual box)
-----------------------------------------

- Chrome 35 (canary) works
- Internet Explorer 11 works but all css styling is missing.
- Internet Explorer 10 didn't work (but maybe be because tab tried to open in default browser)
- Firefox 27.0 the canvas is not loading
- Firefox 17.0 the canvas is not loading

Windows 7 Professional 64 bit (real machine)
---------------------------------------------------------
- Firefox 17.0 ESR works
- Internet Explorer 10 seems to require admin permissions to open the visualization server (if you don't have them).
- Internet Explorer 10 opens an unstyled page with no webgl animation. This is to be expected because IE 10 doesn't support webgl.
- Chrome 43.0.2357.124 m works
- Firefox 36.0.3 works

Ubuntu 13.10
------------------
- Firefox 27.0 works
- Chromium Version 32.0.1700.102 Ubuntu 13.10 (32.0.1700.102-0ubuntu0.13.10.1~20140128.970.1) works

Ubuntu 14.04 64 bit
----------------
- Chromium  43.0.2357.81 does not work (Webgl isn't available)
- Chrome
- Firefox 38 works

Ubuntu 14.10 (Python 3.4)
------------------
- Chrome 44.0.2403.39 beta (64-bit)

OSX Mavericks
--------------------
- Safari 7 doesn't load the canvas.
- Works on Firefox 27.0.1
- Get lots of JS errors (like socket errors) on Chrome 33.0.1750.152

OSX Yosemite (Python 3.4)
--------------------
- Chrome 43.0.2357.124 (64-bit)

**Comment by moorepants** [comment]
@pydy/pydy-developers Would everyone mind trying pydy HEAD of master with whatever OS/browser combos that you have on your computer(s) and listing the results here?

I recommend trying both the mass_spring_damper IPython notebook example and the three_link_conical_pendulum browser display (no notebook).

**Comment by oliverlee** [comment]
mass_spring_damper:
Unreadable Notebook: /home/oliver/repos/pydy/examples/mass_spring_damper/mass_spring_damper.ipynb Unsupported nbformat version 4

three_link_conical_pendulum:
It works using this branch: https://github.com/oliverlee/pydy/tree/enh-update-to-python3

**Comment by moorepants** [comment]
These notebooks require IPython 2.4+ I think. Right now it only works perfectly on IPython 3+.

**Comment by oliverlee** [comment]
Okay I get this error with mass_spring_damper:
/usr/local/lib/python3.4/dist-packages/sympy-0.7.7.dev-py3.4.egg/sympy/matrices/matrices.py in __add__(self, other)
    568                 rv = rv.reshape(*A.shape)
    569             return rv
--> 570         raise TypeError('cannot add matrix and %s' % type(other))
    571 
    572     def __radd__(self, other):

TypeError: cannot add matrix and <class 'list'>

at this line:
sys = System(kane)

**Comment by moorepants** [comment]
You are using SymPy < 0.7.6?

**Comment by oliverlee** [comment]
sympy-0.7.7.dev

**Comment by moorepants** [comment]
That should work. In SymPy 0.7.6 all of the internal lists in KanesMethod were changed to sympy Matrices. And these errors have popped up. What is higher up in the traceback? In particular what line in system.py?

**Comment by moorepants** [comment]
Oh, on initialization of a System. I see.

**Comment by moorepants** [comment]
Does it give the exact line number in system that fails?

**Comment by moorepants** [comment]
Do you have the latest setuptools installed? The version check for the `.dev` is probably failing because you may have an old setuptools.

**Comment by moorepants** [comment]
See: https://github.com/pydy/pydy/pull/166

**Comment by moorepants** [comment]
This only matters when you are using a development version of SymPy.

**Comment by oliverlee** [comment]
uaux and uauxdot are lists I think:
https://github.com/pydy/pydy/blob/e9f7fabcf4befba79e6477aaab1792bc7970c27c/pydy/system.py#L539-540

**Comment by moorepants** [comment]
Oh yeah, that is a little detail. But why are uaux and uauxdot used in the mass spring damper example?

**Comment by moorepants** [comment]
Got it. I don't understand why this fails for you and for me or on travis. There's got to be a slight difference somewhere.

**Comment by moorepants** [comment]
So on 539, the `[:]` may need to be removed.

**Comment by moorepants** [comment]
Hmm, _uaux for me is a Matrix:

```
In [1]: from pydy.models import multi_mass_spring_damper

In [2]: sys = multi_mass_spring_damper()

In [3]: sys.eom_method._uaux
Out[3]: Matrix(0, 0, [])
```

**Comment by moorepants** [comment]
This error is got to be because you have setuptools < 8 installed.

**Comment by oliverlee** [comment]
I'll check later

**Comment by oliverlee** [comment]
In [1]: import setuptools

In [2]: setuptools.__version__
Out[2]: '17.1.1'

**Comment by moorepants** [comment]
So the utils.sympy_newer_than is sending things down the wrong code path in your above traceback. You should try running that function, I don't know why it isn't working. Does the test for that function pass on your machine?

**Comment by oliverlee** [comment]
Which tests? Also I get a new error with a different stack trace so I'm looking at that now.

**Comment by oliverlee** [comment]
Whoops error with this: https://github.com/oliverlee/pydy/commit/a01907b163b1cdfb743ff6119a9b8681b30e9e33

**Comment by moorepants** [comment]
This test should pass: https://github.com/pydy/pydy/blob/master/pydy/tests/test_utils.py

**Comment by oliverlee** [comment]
sympy.physics.mechanics tests show a different way of importing the local modules.

Is this okay? https://github.com/oliverlee/pydy/commit/fa261335d1f066b437880ed694d79bc901e12083

**Comment by moorepants** [comment]
I'm not sure if that is good. I have been changing all of my code to those explicit relative imports over the past few years. I think I was doing that to deal with the fact that absolute imports had changed in python.

I don't know off hand what is the correct choice here. I forget exactly why I started doing relative imports and would have to look things up again to see what the best practice is.

**Comment by oliverlee** [comment]
Both examples run and all tests pass on my computer now with this commit: https://github.com/oliverlee/pydy/commit/920fe1a64d3f3a6ad3cd1fdd530f29aa000da691

Chrome Version 44.0.2403.39 beta (64-bit)
Ubuntu 14.10 64-bit

**Comment by moorepants** [comment]
Cool, want to open a PR?

**Comment by moorepants** [comment]
This is with Python 3?

**Comment by oliverlee** [comment]
oliver@arcturus:~$ python --version
Python 3.4.2

**Comment by moorepants** [comment]
Awesome!

**Comment by moorepants** [comment]
I'm going to try this out on Windows before closing and making the release.

Has anyone tried it out on a Mac yet?

**Comment by oliverlee** [comment]
Yeah I did. I edited the original post.

**Comment by moorepants** [comment]
Ok thanks!

**Comment by moorepants** [comment]
I'm closing this. We have verification that it works in at least one browser on each OS. Firefox and Chrome likely work on all OSes.
