### ISSUE TITLE
Master is failing on travis-ci

### ISSUE THREAD

**Issue by isuruf** [pydy/pydy#361]
https://travis-ci.org/isuruf/pydy/builds/174572164

**Comment by isuruf** [comment]
This is due to changes to CSE in sympy and the subexpressions found are different now.

**Comment by certik** [comment]
@isuruf do you know what to do in order to fix the failure?

**Comment by isuruf** [comment]
I know the reason for the failure, but needs input on how to solve it though.
Main issue is that the result of code-generation of cse'd expressions is hard-coded n tests to make sure it matches.

**Comment by certik** [comment]
@moorepants, how do you want to proceed? This is a blocker for #360.
