### ISSUE TITLE
generated rhs function causes NameError

### ISSUE THREAD

**Issue by mjfwest** [pydy/pydy#389]
In a slightly modified version of the pendulum example, when adding configuration constraints, I receive the following error when evaluating the RHS function returned by `generate_ode_function`  
```python
right_hand_side = generate_ode_function(forcing_vector, coordinates,
                                        speeds, constants,
                                        mass_matrix=mass_matrix,
                                        specifieds=specified,
                                        constants_arg_type='dictionary',
                                        specifieds_arg_type='dictionary'
                                       )

# Set initial conditions, parameter values and time array.
x0 = np.zeros(len(coordinates) + len(speeds))
numerical_constants = {L:1.0, # Length m,
                       m:1.0, # Mass kg,
                       g:9.81}# acceleration due to gravity m/s**2
numerical_specified = {thrust:np.zeros(1)}

right_hand_side(x0, 0.0, numerical_specified, numerical_constants)
NameError: name 'Derivative' is not defined
```
The full non working example is [here as a Gist](https://gist.github.com/mjfwest/3e8f5fcb0f04b77ac5edbd41f1aede33)

**Comment by moorepants** [comment]
The full example would be needed to debug, but it is clear you have not eliminated all derivatives from your forcing_vector.

**Comment by mjfwest** [comment]
Thanks for your comment; I'll have another think.  Please see the edit with the full example.

**Comment by moorepants** [comment]
Closing, likely due to not eliminating q dots.

**Comment by BAmercury** [comment]
> Closing, likely due to not eliminating q dots.

I'm having the same trouble trying to eliminate the q dots from my equations. Do you have any suggestions?

**Comment by Peter230655** [comment]
let's say, you have  $\dot q$, and you want it replaced by $expression4

**Comment by Peter230655** [comment]
There is something about this in sympy issue #24709.
This is what I meant, it started with my simulation.
