### ISSUE TITLE
mass spring damper example visualization 

### ISSUE THREAD

**Issue by Foadsf** [pydy/pydy#412]
I'm trying to run [this example](https://nbviewer.jupyter.org/github/pydy/pydy/blob/master/examples/mass_spring_damper/mass_spring_damper.ipynb), aside from these small issues:

- updating `fr, frstar = kane.kanes_equations([mass], [(P, forces)])`
- removing `%load_ext version_information`
- removing `%version_information pydy, numpy, scipy`

the visualization doesn't work:

![2019-05-29_14-21-14](https://user-images.githubusercontent.com/12762442/58556776-1a650000-821d-11e9-8b0e-264666cc6f04.gif)

or at least I don't know how it should be displayed ¯\\\_(ツ)\_/¯

**Comment by moorepants** [comment]
See https://github.com/pydy/pydy/issues/388

**Comment by Foadsf** [comment]
@moorepants thanks. it works now. but two small issues:

- the mass moves horizontally 
- the panel is unnecessarily too big!

![2019-05-29_15-41-35](https://user-images.githubusercontent.com/12762442/58561833-55206580-8228-11e9-94d9-df210c73dbab.gif)

**Comment by moorepants** [comment]
Both are bugs, please search for existing issues regarding them or open new issues if you don't find one. The visualizer is currently in a state of decay due to Jupyter changing its core widgets code and we not keeping up. See the issue about moving to pythreejs.

**Comment by moorepants** [comment]
If you want to use it as it was, you need to downgrade Jupyter and associated packages to version 4. See notes in the README and the pydy-optional package which does this automatically.

**Comment by Foadsf** [comment]
- the issue about moving to pythreejs [here](https://github.com/pydy/pydy/pull/297)
- README of this example does not mention anything about downgrading Jupyter
- Are you talking about [this conda package](https://anaconda.org/conda-forge/pydy-optional)? How about pip? I do use pip unfortunately.

**Comment by moorepants** [comment]
Yes, that is the issue.

The readme does say explicitly what jupyter versions work: https://github.com/pydy/pydy#installation

Yes, that is the conda package. If you install via pip using the specified optional item `pip install pydy[examples]` it will downgrade the jupyter to version 4.
