### ISSUE TITLE
Example Improvement with gallery

### ISSUE THREAD

**Issue by moorepants** [pydy/pydy#44]
- Include examples in an example "gallery" in the docs. Ideally each example has a visualization of the motion.
- Examples should be run as unit tests, or at least doc tests. It would be nice to have the code for the example as separate and executable but also embedded in the docs (maybe even tutorial style).

**Comment by chrisdembia** [comment]
@jcrist with @moorepants

**Comment by jcrist** [comment]
Based on the folders in `/examples`, here's what we need to do:

- [ ] babyboot
- [ ] body_with_arm
- [ ] chaos_pendulum
- [ ] differential_drive
- [ ] double_pendulum
- [ ] inertia_of_torus
- [ ] Kane1985
- [ ] language_templates
- [ ] mass_spring
- [ ] mass_spring_damper
- [ ] npendulum
- [ ] parallel-execution
- [ ] rattleback
- [ ] rollingdisc
- [ ] sliding_ladder
- [ ] three_link_conical_pendulum
- [ ] tutorials

**Comment by jcrist** [comment]
Edit the above comment to dibs one, then x it when it's done.

**Comment by jcrist** [comment]
## Proposed format

Format:

1. Title
2. Problem Setup

    This should include a vector drawing of the system (see the differential drive or n-pendulum examples, as well as a basic description of said drawing, and what we're trying to solve for.

3. Build System

    Whatever title headers you want here. Should lead through the development and solution of the EOM. Be descriptive, but not verbose. Slightly better than well commented code.

4. Simulation

    Optional. If used, should include pretty matplotlib plots, or a simulation with the viewer (never used this, not sure what to do with that).

### Style:

Because `nbconvert` does some fun things with html tags, a uniform style might be nice. 

- Continuous sections of prose should be merged into the same cell (don't have two adjacent text cells). 
- Title should be heading 1 (single `#`) and in its own cell. 
- Subheaders should be included in the same cell as any following text, and should progress logically down the heading hierarchy (subsection under heading `n` with heading `n + 1`).

**Comment by chrisdembia** [comment]
+1

**Comment by moorepants** [comment]
+1

Talk to Tarun, but the ideal situation is that if the notebook has a visualization, nbconvert would somehow retain it (the visualizations are not necessarily tied to the "server" side) so nbviewer, for example, should be able to show it.

**Comment by moorepants** [comment]
@jcrist I was thinking about PR #137  and I think I'm -1 to enforcing the notebook format. I think we should support a pure script format and a notebook format for the examples. Creating the notebooks adds a lot of overhead and it takes time to do it well.

**Comment by jcrist** [comment]
Enforcing it - maybe not. However, for things we link to off the site directly, I think the examples should have some effort put into them. For the TU Delft examples, putting them all in a folder, with a readme is probably good enough, and then just linking to that on github. But things that should be online-viewable I still think should have a diagram, some prose, code, and results all displayed, and downloadable by the user. And the easiest way to do that is to use a notebook.

**Comment by moorepants** [comment]
Take for example the matplotlib examples. All they typically show are the plot image in the gallery and then you click it to see the image(s) and the code (script) that produced them. I can imagine a parallel that shows a diagram or screenshot from the 3D viewer and links to the script that produces it. And then secondly we can have the same type of thumbnails that link to embedded ipython notebooks that show a more in depth example with maths, images, prose, etc.

So maybe we have two templates (or specifications) for examples. One being yours above and another that just requires a diagram, thumbnail, and script(s). What do you think?

**Comment by jcrist** [comment]
Sounds good to me. I just want to make sure we don't end up with a bunch of scripts with no diagrams or prose. Any examples we link to directly from the gallery should have some effort put into them. A diagram (and a thumbnail version), as well as some prose about what the example is wouild be a minimal requirement.

**Comment by moorepants** [comment]
Jim and I discussed the example gallery at SciPy. Here is the synopsis:

- The structure of the examples should facilitate two things:
  1. Enable the ability to run all examples with a single script
  2. Allow us to scrape the example directory and create a gallery for the website.
- We are modelling our gallery after matplotlib's and bokeh's
- Each directory `examples` represents 1 example.
- An example directory can contain a script (or scripts) or a notebook (plus scripts).
- Each example directory will contain a config file (we need to choose yaml, json, ini, or something). Contents:
  - `title`: A title for the example
  - `build_command`: this gives the relative path to a shell command that will execute the full example
  - `thumbnail`: this will give the relative path to an image that can be used as a thumbnail on the gallery
  - `code`: this will contain a relative path to the either the python script that has code you want to display under the example or the relative path to the notebook that should be converted for the example. If nothing is provided it will generate the url to this example folder to place on the example's gallery page.
- The example must, at the bare minimum have a `build_command`, but if it has no other info the example will not be shown on the website gallery page.
- If there is no thumbnail image specified it will make a thumbnail from the code.
- The README should be present explaining the example and it will automatically be parsed and added under the example image in the gallery page. The readme will display above the convereted notebook on a gallery page (it may have dep install instructions, for example).
- The gallery page will be a grid with uniform width thumbnails. When you click a thumbnail you are taken to that example's page that contains thumbnail, readme text, and code (or notebook).

**Comment by moorepants** [comment]
I'm trying out jupyter_sphinx in PR #419 and it produces quite a nice result. I'm thinking that all examples should be moved to this format.

**Comment by moorepants** [comment]
Jupyter sphinx is now used and a basic gallery is in place. See #422 to continue moving examples over.
