### ISSUE TITLE
Documentation link to Mass-Spring-Damper example is broken

### ISSUE THREAD

**Issue by als0052** [pydy/pydy#441]
Navigating from this page: https://pydy.readthedocs.io/en/stable/tutorials/beginners.html and clicking on the Mass Spring Damper example takes you to a 404-error page 

error page url: 
https://nbviewer.jupyter.org/github/pydy/pydy/blob/master/examples/mass_spring_damper/mass_spring_damper.ipynb

![image](https://user-images.githubusercontent.com/43427976/95979111-238e4700-0de9-11eb-990f-cc9f282ee48e.png)

**Comment by moorepants** [comment]
Thanks. We are working on moving the examples in the the documentation (see #422). I'll fix the link but it has been transferred here:

https://pydy.readthedocs.io/en/latest/examples/mass-spring-damper.html

You can see the start of the gallery here:

https://pydy.readthedocs.io/en/latest/#examples

**Comment by moorepants** [comment]
The link has been fixed in the master branch.
