### ISSUE TITLE
Integrating system model fails (sometimes!)

### ISSUE THREAD

**Issue by jdekarske** [pydy/pydy#455]
I'm not sure if this is a pydy issue or scipy, but I'll start here. Working off the [human standing model](https://github.com/pydy/pydy-tutorial-human-standing), I've created a two linkage robot model. Everything is similar but I've added reference scaling for the closed loop controller to feed desired thetas ([see .ipynb here](https://github.com/jdekarske/2d-robot-prognostics/blob/main/robotdynamics.ipynb)). Upon integrating with odeint, I receive one of a few results:

Expected:
![expected](https://user-images.githubusercontent.com/20480052/129137292-b2b2d880-d4a2-425f-8c25-9f0d18ec73a5.png)

Unstable:
![unstable1](https://user-images.githubusercontent.com/20480052/129137394-a0629a94-8bd5-4291-a849-20d580229b29.png)
With this warning:
```
.venv/lib/python3.8/site-packages/scipy/integrate/odepack.py:247: ODEintWarning: Excess work done on this call (perhaps wrong Dfun type). Run with full_output = 1 to get quantitative information.
  warnings.warn(warning_msg, ODEintWarning)
```

The odd thing is that I'll swap between good and bad results at random by only restarting the ipython kernel and running all the cells again. I have not been able to reproduce this consistently. Any help would be awesome, thanks!

---
Maybe related
```
from __future__ import print_function, division
from sympy import symbols, simplify, pi
from sympy.physics.mechanics import dynamicsymbols, ReferenceFrame, Point
from sympy.physics.vector import init_vprinting
from pydy.system import System
import numpy as np
init_vprinting(use_latex='mathjax', pretty_print=False)

importing from sympy.printing.ccode has been deprecated since SymPy
1.7. Use Import from sympy.printing.c instead. See
https://github.com/sympy/sympy/issues/20256 for more info.
```

```
$ pip freeze
argon2-cffi==20.1.0
async-generator==1.10
attrs==21.2.0
autopep8==1.5.7
backcall==0.2.0
bleach==3.3.0
cffi==1.14.5
cycler==0.10.0
decorator==5.0.9
defusedxml==0.7.1
entrypoints==0.3
ipydatawidgets==4.2.0
ipykernel==5.5.5
ipython==7.24.0
ipython-genutils==0.2.0
ipywidgets==7.6.3
jedi==0.18.0
Jinja2==3.0.1
jsonschema==3.2.0
jupyter-client==6.1.12
jupyter-core==4.7.1
jupyterlab-pygments==0.1.2
jupyterlab-widgets==1.0.0
kiwisolver==1.3.1
MarkupSafe==2.0.1
matplotlib==3.4.2
matplotlib-inline==0.1.2
mistune==0.8.4
mpmath==1.2.1
nbclient==0.5.3
nbconvert==6.1.0
nbformat==5.1.3
nest-asyncio==1.5.1
notebook==6.4.0
numpy==1.21.0
packaging==20.9
pandas==1.3.0
pandocfilters==1.4.3
parso==0.8.2
pexpect==4.8.0
pickleshare==0.7.5
Pillow==8.3.0
prometheus-client==0.11.0
prompt-toolkit==3.0.18
ptyprocess==0.7.0
pycodestyle==2.7.0
pycparser==2.20
pydy==0.6.0.dev0
Pygments==2.9.0
pyparsing==2.4.7
pyrsistent==0.18.0
python-dateutil==2.8.1
pythreejs==2.3.0
pytz==2021.1
pyzmq==22.1.0
scipy==1.7.0
Send2Trash==1.7.1
six==1.16.0
sympy==1.8
terminado==0.10.1
testpath==0.5.0
toml==0.10.2
tornado==6.1
traitlets==5.0.5
traittypes==0.2.1
wcwidth==0.2.5
webencodings==0.5.1
widgetsnbextension==3.5.1
```

**Comment by moorepants** [comment]
These kinds of issues are more tied to selecting the correct integration routine and/or or settings for that particular problem. PyDy does the most basic thing by default and uses the default settings for scipy's odeint. You can pass in custom integrators to the system object to configure things more carefully. That's my guess without looking into this closely.

**Comment by jdekarske** [comment]
I've tried all the integration methods in solve_ivp, but I'll have to play with the solver options, thanks!

**Comment by moorepants** [comment]
It could be something with the controller design. Maybe it's making a too stiff controller?
