### ISSUE TITLE
Alternatives to generate_ode_function 

### ISSUE THREAD

**Issue by Simone2021space** [pydy/pydy#457]
Hi,
I noticed that generate_ode_function doesn't work when using a nested Piecewise function (which contains an ITE statement).
Are there alternatives to it, like lambdify? How to use it?

**Comment by moorepants** [comment]
Yes, lambdify can be used, but you'll set it up correctly. Here's an example with resonance that might give some ideas:

https://github.com/moorepants/resonance/blob/f7f8550830e6a7e35f595acbbfaffad86174abd8/notebooks/10/10_modeling_a_ball_channel_pendulum.ipynb

**Comment by moorepants** [comment]
And the lambdify documentation: https://docs.sympy.org/latest/modules/utilities/lambdify.html

**Comment by moorepants** [comment]
You'll have to manually create your own function using lambdify or hand craft the underlying code you need to run in your integrator. We could try to support ``Piecewise`` objects in the c code generator, but you'll need to provide a simple example we can use a test. Maybe adding a wall that the spring, mass, damper example could hit or something. Closing this for now. Reopen if there is more info.
