### ISSUE TITLE
"Exception: Failed to compile and import Cython module" - Carvallo-Whipple Bicycle Model

### ISSUE THREAD

**Issue by JeswinKoshyCherian** [pydy/pydy#460]
Line 227 of carvallo-whipple.py (from https://pydy.readthedocs.io/en/latest/examples/carvallo-whipple.html)

`sys.generate_ode_function(generator='cython')`

gives:

`File "D:\Miniconda3\envs\pydy-dev\lib\site-packages\pydy\codegen\cython_code.py", line 227, in compile
    raise Exception('Failed to compile and import Cython module.')`

`Exception: Failed to compile and import Cython module.`

**Comment by moorepants** [comment]
You should try out a simple Cython example manually to see if your cython and compiler are properly setup. It seems that `conda install cython` on your computer hasn't properly set things up. So you could try out this example in cython tutorial: https://cython.readthedocs.io/en/latest/src/tutorial/cython_tutorial.html. If that works, then it should work for the pydy example.

**Comment by moorepants** [comment]
My guess is that you don't have a working MSVC compiler installed.

**Comment by JeswinKoshyCherian** [comment]
Ran the example in the Cython tutorial which gave an error 
`error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/`

Downloading it solved the problem
