### ISSUE TITLE
Question: Is it possible to obtain needed torque to drive mechanism according to motion of an endpoint

### ISSUE THREAD

**Issue by ManuelZ** [pydy/pydy#463]
Hi, 

I'd like to ask if, given a mechanism and a desired motion of an "output" link, is it possible to obtain the needed torque in the "input" link to drive it.

Thanks

**Comment by moorepants** [comment]
Yes, it is possible. If you are asking whether this library has features for doing so, the answer is no.

**Comment by ManuelZ** [comment]
Yes, I was asking if this library could do that. Ok, thanks.
