### ISSUE TITLE
pythreejs animations no longer display in the documentation

### ISSUE THREAD

**Issue by moorepants** [pydy/pydy#493]
There have been some recent updates to pythreejs and ipywidgets that have likely caused things to break.

![image](https://user-images.githubusercontent.com/276007/227706378-14bc3587-880e-4aba-a007-c78aa7c22620.png)

Same issue in my book, some more notes are here: https://github.com/moorepants/learn-multibody-dynamics/issues/149

**Comment by moorepants** [comment]
This was somehow resolved upstream. Not sure what changed.

**Comment by merlinND** [comment]
Hello @moorepants,

I believe that the breaking change in ipywidgets was reverted (https://github.com/jupyter-widgets/ipywidgets/pull/3830) after a request from @vidartf (https://github.com/jupyter-widgets/ipywidgets/issues/3735#issuecomment-1591057532). At least the last time I looked at it.

**Comment by moorepants** [comment]
This issue is still open: https://github.com/jupyter-widgets/pythreejs/issues/389
