### ISSUE TITLE
Newton-Euler dynamics algorithm

### ISSUE THREAD

**Issue by Simone2021space** [pydy/pydy#496]
Hi community,
is there an implementation of Newton-Euler recursive algorithm in PyDy?

**Comment by Peter230655** [comment]
You have Kane's method and Lagrange's method (the latter I have never used) in sympy.physics.mechanics.
I have never come across Newton-Euler's recursive algorithm, of course it may still be there.

**Comment by moorepants** [comment]
SymPy Mechanics does not have any recursive dynamics algorithm's implemented. There is this open PR from some years back: https://github.com/sympy/sympy/pull/11415
