### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by Peter230655** [pydy/pydy#498]
When I use _pydy.System_ to numerically integrate some system (the EOMs of some multibody system) does it allow that the integration be interrupted when some event occurs? I could not find anything in the documentation.
scipy's _solve_ivp_ does allow it, so I am wondering.
**Thanks!**

**Comment by moorepants** [comment]
By default no, but you can use any ODE solver you want to and set it up to detect events:

https://pydy.readthedocs.io/en/stable/system.html#pydy.system.System.integrate

**Comment by Peter230655** [comment]
**Thanks!**
![image](https://github.com/pydy/pydy/assets/83544146/98ce37d4-93d9-4bb4-b7b8-72fe5c40727c)
solve_ivp would not work, as its signature is not as required?

**Comment by moorepants** [comment]
You can create a function to wrap solve ivp with the arguments as pydy needs them.

**Comment by Peter230655** [comment]
Stupid question on my part! I could have thought of this myself.
