### ISSUE TITLE
Tests error for Attributes missing

### ISSUE THREAD

**Issue by Moraxyc** [pydy/pydy#500]
Hello,

In the maintenance work in `nixpkgs`, we noticed that there are many `AttributeError` throw during the check phase after we changed `nose` to `pynose`.

```
test_c_code
test_cython_code
test_scene
test_system
test_ode_function_generator
```

```
E       AttributeError: 'TestCMatrixGenerator' object has no attribute 'generator'
E       AttributeError: 'TestCythonMatrixGenerator' object has no attribute 'generator'
E       AttributeError: 'TestODEFunctionGenerator' object has no attribute 'rhs'
E       AttributeError: 'TestODEFunctionGenerator' object has no attribute 'sys'
E       AttributeError: 'TestODEFunctionGeneratorSubclasses' object has no attribute 'sys'
E       AttributeError: 'TestSystem' object has no attribute 'kane'
E       AttributeError: 'TestSystem' object has no attribute 'sys'
E       AttributeError: 'TestScene' object has no attribute 'ref_frame'
```

Full test log is [here](https://github.com/pydy/pydy/files/15403868/pydy-test.log)

**Comment by moorepants** [comment]
Thanks. Is pynose a new fork of nose?

**Comment by Moraxyc** [comment]
https://pypi.org/project/pynose

I'm not familiar with nose, but it seems that these errors were not caused by switching to pynose.

If you have any suggestions, please feel free to tell me.

**Comment by Moraxyc** [comment]
[pytest-log-with-nose.log](https://github.com/pydy/pydy/files/15404692/pytest-log-with-nose.log) 
Here is the log of the test using `nose`.

**Comment by moorepants** [comment]
Maybe they re issues with newer Python versions.

I had a look at pynose and noticed it does not abide by the LGPL of nose, so be careful if you are packaging and redistributing with nix.

I'll likely switch to py.test here next time I make a release.

**Comment by moorepants** [comment]
I ran nosetests on the tip of master:

```
$ nosetests pydy
/home/moorepants/src/pydy/pydy/codegen/tests/test_ode_function_generator.py:275: PyDyImportWarning: Theano was not found so the related tests are being skipped.
  warnings.warn("Theano was not found so the related tests are being"
....................................................................../home/moorepants/src/pydy/pydy/tests/test_system.py:414: PyDyImportWarning: Theano was not found so the related tests are being skipped.
  warnings.warn("Theano was not found so the related tests are being"
..........
----------------------------------------------------------------------
Ran 80 tests in 37.560s

OK
```

**Comment by moorepants** [comment]
Are you running pytest and not nose? The logs you show look like pytest output. Currently this package's tests do not support pytest or pynose. It only supports the original nose.

**Comment by Moraxyc** [comment]
Yes I use pytest like the last maintainer of pydy in Nixpkgs did.

I’d like check again with `nosetests`

**Comment by moorepants** [comment]
pytest dropped support for nose style tests sometime recently, so the errors you report are expected given that we don't support pytest.

**Comment by Moraxyc** [comment]
I'm sorry for taking up your timem

We rewrote the check phase using `nosetests`, still using pynose, and the results were ok. 

Thank you for your answer!
