### ISSUE TITLE
[Viz: GUI] Unable to change color when material is default

### ISSUE THREAD

**Issue by tarzzz** [pydy/pydy#85]
When the material is set to Default in GUI, Color is not shown on the objects, while it works fine when other material(Other than default) is chosen

**Comment by sahilshekhawat** [comment]
This is a very strange bug. It works if I pass hex values but doesn't work with color names. Moreover, when we are setting color value of the material here:https://github.com/pydy/pydy/blob/master/pydy/viz/static/js/dyviz/scene.js#L233 
Color property in material is grey but when I do console.log(material.color) it shows me red. A hack can be to convert color names to hex values but still we need to fix this.

**Comment by moorepants** [comment]
I don't know the details of the code, but we originally defined colors with hex values and things worked. The change to color key words introduced this bug.

**Comment by sahilshekhawat** [comment]
So, should we just implement the hack to convert color names to hex value? because this is very strange. I have looked into entire visualization's implementation and it should work but its not. If we decide to not implement this hack now, I will look into it whenever I have time as I have spent a lot  of time on it for now. Does that sound reasonable?

**Comment by moorepants** [comment]
The hack seems like a reasonable fix for now.

**Comment by sahilshekhawat** [comment]
Okay, on it :+1:

**Comment by sahilshekhawat** [comment]
Found the bug! :smile: 
So, we have an array called self.Materials which have all the materials but problem is that they are objects and thus, only the last color value is applied to all the system since its all made from single material. We just need to create an object everytime.

**Comment by moorepants** [comment]
Nice!
