### ISSUE TITLE
Make issues for all outstanding issues in the motion-dev PR

### ISSUE THREAD

**Issue by moorepants** [pydy/pydy#88]
There are a ton of issues and feature requests in PR #82 that need to be move into the issue tracker and categorized.

**Comment by moorepants** [comment]
@tarzzz Can you go through PR #82 and check off things that have been solved and then move any relevant unsolved issues to the issue tracker?

**Comment by tarzzz** [comment]
Most of them are addressed. The main one which is still un-resolved:
 - Shape Color change: Even if we change color from the object editor, it does not seems to be reflected in the viz. Its a bug, adding in the issue tracker.

**Comment by moorepants** [comment]
Ok, please open new issues for anything like that.

**Comment by moorepants** [comment]
@tarzzz Is this done? If so please close this issue.

**Comment by moorepants** [comment]
Closing.
