### ISSUE TITLE
Trackball controls broken, when user defined camera is added

### ISSUE THREAD

**Issue by tarzzz** [pydy/pydy#94]
When A custom camera is added from Python side to Scene, the trackball controls do not work

**Comment by moorepants** [comment]
@tarzzz If we are not going to fix the custom camera code it needs to be removed from master and moved either to a WIP PR or to the trash.

**Comment by tarzzz** [comment]
I will add a patch real soon, to fix the custom camera code. We can keep it in the master for a few days, and apply a patch code to it to make it work.

**Comment by moorepants** [comment]
So you are suggesting we fix the feature instead of remove it?
